fairlearn/fairlearn

README.md
fairlearn/classred.py
fairlearn/moments.py
test_fairlearn.py

Plus remove redundant parentheses.
Tests pass before and after, with Python 3.7.0 on macOS High Sierra:
```console
$ python test_fairlearn.py
testing (DP, eps=0.100): ok
testing (DP, eps=0.050): ok
testing (DP, eps=0.020): ok
testing (DP, eps=0.010): ok
testing (DP, eps=0.005): ok
testing (EO, eps=0.100): ok
testing (EO, eps=0.050): ok
testing (EO, eps=0.020): ok
testing (EO, eps=0.010): ok
testing (EO, eps=0.005): ok
```

Fix some flake8 warnings and fix a Python typo

---

fairlearn/classred.py

using FairLearn throws 2 FutureWarnings
```
fairlearn/classred.py:309: FutureWarning: The 'contains' method is deprecated and will be removed in a future version. Use 'key in index' instead of 'index.contains(key)'
```
```
fairlearn/classred.py:358: FutureWarning: The 'contains' method is deprecated and will be removed in a future version. Use 'key in index' instead of 'index.contains(key)'
```
This PR just implements the suggested changes

updated to "key in index" from "contains" to suppress FutureWarning

---

fairlearn/reductions/grid_search/grid_search.py
fairlearn/reductions/grid_search/quality_metric.py
fairlearn/reductions/grid_search/simple_quality_metrics.py
notebooks/Grid Search for Binary Classification.ipynb
notebooks/Grid Search with Census Data.ipynb
test/reductions/grid_search/test_grid_search_classification.py
test/reductions/grid_search/test_grid_search_regression.py

Some argument renaming for GridSearch
- kwarg `protected_attribute` becomes `aux_data` in `GridSearch`
- For quality metrics, replace `protected_attribute` with `bin_id`

Argument Renaming

---

azuredevops/code-coverage.yml

We don't need to run code coverage for every PR or merge

Turn off code coverage for PR and CI

---

fairlearn/metrics/__init__.py
fairlearn/metrics/bounded_group_loss.py
fairlearn/metrics/demographic_parity.py
fairlearn/metrics/equalized_odds.py
fairlearn/metrics/metric.py
fairlearn/reductions/grid_search/grid_search.py
notebooks/Grid Search for Binary Classification.ipynb
notebooks/Grid Search with Census Data.ipynb

With the `Moment`-based implementation of `GridSearch` in, remove obsolete code:
- Handwritten reweighting/relabelling in `GridSearch`
- Portions of `metrics` such as `metrics.DemographicParity` which are just used as `enum`s

Remove obsolete `GridSearch` code

---

fairlearn/reductions/__init__.py
fairlearn/reductions/exponentiated_gradient/exponentiated_gradient.py
fairlearn/reductions/grid_search/grid_search.py
fairlearn/reductions/reduction.py
notebooks/Grid Search for Binary Classification.ipynb
notebooks/Grid Search with Census Data.ipynb
test/unit/reductions/grid_search/test_grid_search_demographicparity.py
test/unit/reductions/grid_search/test_grid_search_regression.py

Make naming in `reductions` match `ExponentiatedGradient`
Remove `posterior` methods from `GridSearch` (and base `Reduction` class)

GridSearch and Reductions Rename

---

fairlearn/__init__.py
fairlearn/reductions/grid_search/grid_search.py
fairlearn/reductions/grid_search/grid_search_result.py
test/unit/reductions/grid_search/test_grid_search_arguments.py

Minor improvements for `GridSearch`:
- `GridSearchResult` now uses properties for everything
- `GridSearch` now uses properties for `all_results` and `best_result`, allowing them to be documented
- Add a check on the `predict` and `predict_proba` methods of `GridSearch` to make sure that `fit` has been called previously

GridSearch Properties and Protection

---

devops/code-coverage-job-template.yml

Including the performance tests makes the code coverage build time out

Restrict code coverage build to unit tests

---

devops/all-tests-job-template.yml
requirements-fixed.txt
requirements.txt
scripts/requirementscheck.py
setup.py

Script to check that two requirements files for pip are consistent. Use in the builds to compare `requirements.txt` and `requirements-fixed.txt`
There is no support for `setup.py` at the present time.

Consistency for Requirements

---

fairlearn/metrics/_mean_predictions.py
test/unit/metrics/test_mean_predictions.py

By convention, error metrics decrease towards zero
Update the sign of `mean_underprediction` to reflect this

Fix for mean_underunderprediction

---

setup.py

There were a few lingering references to the dashboard in `setup.py`

Remove dashboard from setup.py

---

devops/notebook-job-template.yml

Having trouble with Python 3.5 in the Notebooks build
Since this was a recent addition, turn it back off pending debug and fix

Turn off Python 3.5 for Notebooks

---

devops/nightly.yml
devops/notebook-job-template.yml
requirements-fixed.txt
requirements.txt

The issue before was that we were catching a ModuleNotFoundError for not having tensorflow/pytorch installed, but ModuleNotfoundError itself doesn't exist in py3.5, so that was generalized in tempeh release v0.1.7 to catch ImportError. Adding notebook test for py3.5 back.

tempeh upgrade to v0.1.7 to fix notebooks in python 3.5

---

fairlearn/reductions/_exponentiated_gradient/_lagrangian.py

Ensure second call to `linprog` uses same algorithm as the first

Bugfix for _Lagrangian

---

fairlearn/metrics/_balanced_root_mean_squared_error.py
fairlearn/metrics/_input_manipulations.py
fairlearn/metrics/_mean_predictions.py
fairlearn/metrics/_metrics_engine.py
test/unit/metrics/test_group_sklearn_wrappers.py
test/unit/metrics/test_input_manipulations.py
test/unit/metrics/test_mean_predictions.py
test/unit/metrics/test_metrics_engine.py

It turns out that `numpy.squeeze([1])` results in a scalar and not a single element array
This was causing trouble with the group metrics when only a single prediction was passed
Issues also showed up in the mean prediction metrics, which made a similar call
Solution is to add a helper function (with tests) to check for this case, and ensure that a `numpy.ndarray` is always returned

Single element fix for group metrics

---

fairlearn/__init__.py

Add logic to `__init__.py` to allow a release candidate number to be specified via an environment variable
The goal of this is to allow us to push different versions to PyPI-Test without affecting the version which is ultimately pushed to PyPI itself

Allow RC specification from environment

---

devops/PR-Gate.yml
devops/nightly.yml
devops/pypi-deployment-stages-template.yml
devops/pypi-release.yml

We're having troubles getting MacOS agents. Try changing to the latest image in case the one we were using is being retired.

Update MacOS Agent

---

test/__init__.py
test/unit/__init__.py
test/unit/input_convertors.py
test/unit/metrics/__init__.py
test/unit/metrics/test_metrics_engine.py
test/unit/reductions/__init__.py
test/unit/reductions/exponentiated_gradient/__init__.py
test/unit/reductions/exponentiated_gradient/simple_learners.py
test/unit/reductions/exponentiated_gradient/test_expgrad_arguments.py
test/unit/reductions/exponentiated_gradient/test_expgrad_smoke.py
test/unit/reductions/grid_search/__init__.py
test/unit/reductions/grid_search/test_grid_search_arguments.py

Create and use a standard set of convertors for use with our 'argument type' tests. This has required adding several `__init__.py` files to the `test` directory to enable `pytest` to find the common code.
Also add an 'argument type' test to `ExponentiatedGradient`

Standardise input convertors for test

---

requirements.txt

The recent update to scikit-learn is causing a break in one of the Notebooks. Until this is debugged, pin the version

Pin scikit-learn

---

notebooks/Mitigating Disparities in Ranking from Binary Data.ipynb
requirements.txt

Tweak the Law School notebook so that it works with the latest `scikit-learn`
This enables us to unpin the version of `scikit-learn` in our `requirements.txt` file

Fix for Law School Notebook

---

fairlearn/__init__.py

Declare 0.4.0 release

---

devops/PR-Gate.yml
devops/nightly-requirements-fixed.yml
devops/nightly.yml
devops/pypi-deployment-stages-template.yml
devops/pypi-release.yml

An issue with the `pip` install of `shap` has appeared on the Linux agents under Python 3.5. Reasons are currently obscure, but this is blocking a release. Since Python 3.5 continues to work on Windows, rely on that (pending further debugging)

Workaround Python 3.5 issue with Linux

---

requirements-fixed.txt
requirements.txt

During our release process, a new version of `colorama` (required by one of our dependencies) was released. This has issues with the Windows/3.7 build.
Unblock the release by pinning the version

Pin troublesome package

---

README.md
requirements-fixed.txt
requirements.txt
visualization/FairnessDashboard/src/FairnessWizard.tsx

The fix for probit placed it above the check for classification, and since a classifier fits the probit check, all binary classifiers would be classified as probits.

fix classification classification bug

---

README.md
requirements-fixed.txt
requirements.txt

Some portions of the v0.4.0 release branch were accidentally merged into master
- Making the ReadMe version suitable for PyPI
- Pinning the `colorama` version to unblock the release train
This changeset undoes these fixes in master

Fix accidental merge

---

CONTRIBUTING.md
README.md
scripts/build-wheels.ps1
scripts/process_readme.py

Create a python script to translate `ReadMe.md` from GitHub to PyPI. This will avoid the need to create a branch to do a release.
This script is slightly dependent on the structure of the file, so if there are substantial changes to that, this script will require updating. It also assumes that a tag `v(fairlearn.__version__)` exists in the repo.

ReadMe Processor for Releases

---

devops/PR-Gate.yml
devops/all-tests-job-template.yml
devops/create-wheel-step-template.yml
devops/nightly-requirements-fixed.yml
devops/nightly.yml
devops/pip-freeze-to-artifact-steps-template.yml
devops/pypi-deployment-stages-template.yml
devops/pypi-release.yml

We've had trouble with our dependencies updating and breaking our builds
Augment the build pipelines so that they publish the output of `pip freeze` to an artifact. This will aid debugging these issues.

Track pip dependencies

---

fairlearn/metrics/_balanced_root_mean_squared_error.py
fairlearn/metrics/_extra_metrics.py
fairlearn/metrics/_group_metric_result.py
fairlearn/metrics/_input_manipulations.py
fairlearn/metrics/_mean_predictions.py
fairlearn/metrics/_metrics_engine.py
fairlearn/metrics/_selection_rate.py
fairlearn/metrics/_skm_wrappers.py
fairlearn/postprocessing/_curve_plotting_utilities.py
fairlearn/postprocessing/_interpolated_prediction.py
fairlearn/postprocessing/_roc_curve_utilities.py
fairlearn/postprocessing/_threshold_operation.py
fairlearn/postprocessing/_threshold_optimizer.py
fairlearn/reductions/_exponentiated_gradient/__init__.py
fairlearn/reductions/_exponentiated_gradient/_exponentiated_gradient_result.py
fairlearn/reductions/_exponentiated_gradient/exponentiated_gradient.py
fairlearn/reductions/_grid_search/grid_search.py
fairlearn/reductions/_grid_search/grid_search_result.py
fairlearn/reductions/_moments/bounded_group_loss.py
fairlearn/reductions/_moments/conditional_selection_rate.py
fairlearn/reductions/_moments/error_rate.py
fairlearn/reductions/_moments/moment.py
fairlearn/reductions/_reduction.py
setup.cfg

After adding more `flake8` analysers, we were obliged to put in some global suppressions to keep the number of issues manageable. Start the process of removing these with D102, D103 and D401. Some of these just move the suppression to file-level, while others tweak documentation blocks to suit.

Remove some flake8 global suppressions

---

devops/all-tests-job-template.yml
devops/code-coverage-job-template.yml
devops/create-wheel-step-template.yml
devops/nightly-requirements-fixed.yml
devops/nightly.yml
devops/notebook-job-template.yml
devops/notebook-pypi-job-template.yml
devops/pypi-deployment-stages-template.yml
devops/pypi-release.yml
devops/python-infra-upgrade-steps-template.yml
devops/unit-tests-pypi-job-template.yml

Roman figured out a workaround for getting `shap` installed with Linux and Python 3.5. Put this into `fairlearn`

Re-enable Linux 3.5

---

devops/PR-Gate.yml
devops/nightly-requirements-fixed.yml
devops/nightly.yml
devops/pypi-deployment-stages-template.yml
devops/pypi-release.yml

Increase the variety of platforms used for testing our Jupyter Notebooks. Unable to test on MacOS at present, due to some problem installing `lightgbm`.

Expand Notebook testing

---

fairlearn/postprocessing/_postprocessing.py
fairlearn/postprocessing/_threshold_optimizer.py
fairlearn/reductions/_exponentiated_gradient/exponentiated_gradient.py
fairlearn/reductions/_grid_search/grid_search.py

Make our documentation of `fit()`, `X`, `predict()` etc. more standard between our various submodules.

Standardise ML argument documentation

---

docs/conf.py
fairlearn/exceptions.py
fairlearn/metrics/__init__.py
fairlearn/metrics/_balanced_root_mean_squared_error.py
fairlearn/metrics/_extra_metrics.py
fairlearn/metrics/_group_metric_result.py
fairlearn/metrics/_skm_wrappers.py
fairlearn/postprocessing/_interpolated_prediction.py
fairlearn/postprocessing/_threshold_optimizer.py
fairlearn/reductions/_exponentiated_gradient/_exponentiated_gradient_result.py
fairlearn/reductions/_grid_search/grid_search_result.py
fairlearn/reductions/_moments/bounded_group_loss.py
fairlearn/reductions/_moments/conditional_selection_rate.py
fairlearn/reductions/_reduction.py
setup.cfg

Various updates for the documentation:
- Remove another `flake8` global suppression
- Add explanations for remaining `flake8` suppressions
- Replace the `:any:` references in the documentation with appropriate ones
- Make some file-level suppressions (which may have actually turned `flake8` off entirely on the file) specific to the appropriate lines

Documentation and flake8

---

devops/pypi-release.yml

The KeyVault containing the PyPI secrets has been moved to a more appropriate subscription. As a result, the Release pipeline needs to be updated with the correct service connection

Update Release pipeline after KV move

---

test/unit/reductions/moments/__init__.py
test/unit/reductions/moments/data_generator.py
test/unit/reductions/moments/test_moments_demographic_parity.py
test/unit/reductions/moments/test_moments_equalized_odds.py

Some very basic unit tests for the `EqualizedOdds` and `DemographicParity` moment classes. These are 'pinning' tests two establish the behaviour of these classes. The `gamma` method is not yet included in these tests, since that requires a trained model.

Basic unit tests for EqualizedOdds and DemographicParity moments

---

devops/all-tests-job-template.yml
devops/code-coverage-job-template.yml
devops/notebook-job-template.yml
devops/notebook-pypi-job-template.yml
devops/unit-tests-pypi-job-template.yml
notebooks/Group Metrics.ipynb
requirements.txt
test/notebooks/__init__.py
test/notebooks/test_group_metrics_nb.py
test/notebooks/test_notebooks.py
test/perf/test_performance.py
test/pytest.ini

Rather than using `nbval`, convert our notebook tests to use `papermill`. With the help of `nteract-scrapbook` we can then examine the contents of particular variables from the notebooks to ensure that we're getting the expected results.
Explicit `scrapbook` commands are required to save out values for future examination, but we don't want to include these when our users look at the notebooks. Accordingly, we include machinery for adding the necessary cells to the notebooks dynamically.

Convert Notebook tests to papermill

---

devops/templates/code-coverage-job-template.yml
devops/templates/python-infra-upgrade-steps-template.yml
requirements.txt

They'll unexpectedly succeed otherwise and that will cause the check to fail.

Exclude install tests in code coverage check

---

fairlearn/metrics/_group_metric_set.py
fairlearn/widget/_fairlearn_dashboard.py

The dashboard already had its own keys defined for mapping metric functions to strings. Update the `GroupMetricSet` to use the same keys.
Figuring out how to unify the two implementations of this mapping is left as a issue #269 

Update metric keys to match dashboard

---

scripts/build_wheels.py

Env var needs to be set before installing fairlearn to make the written version of the package correct. Currently it doesn't include "dev<number>" if it's the test configuration.

Fix build wheels script

---

CHANGES.md
fairlearn/exceptions.py
fairlearn/postprocessing/_threshold_optimizer.py
fairlearn/reductions/_grid_search/grid_search.py
test/unit/reductions/grid_search/test_grid_search_arguments.py

Fixes #253.
This PR replaces `NotFittedException` with `sklearn.exceptions.NotFittedError`, and removes the `exceptions.py` file, since that exception was the only on present in it.

MNT use sklearn's NotFittedError instead of NotFittedException

---

fairlearn/metrics/_group_metric_result.py
fairlearn/metrics/_group_metric_set.py
test/unit/metrics/test_group_metric_result_comparison.py
test/unit/metrics/test_group_metric_set.py

Add (in)equality operators to `GroupMetricResult` and `GroupMetricSet`, along with basic tests. These will simplify other testing in future.
Change `GroupMetricSet` so that the `groups` have to be specified as sequential integers from zero. If this is not the case then the `compute()` method will remap the supplied groups to `[0, 1, 2, ….]` and put the stringified original values into the `group_names` property. Since the keys are now sequential integers, convert the `group_names` property itself from a dictionary into a list.
Closes #275

Updates for GroupMetricResult and GroupMetricSet

---

CONTRIBUTING.md

This PR trims the lines in the contributing guide, and adds this note:
```
It basically means you need to sign off your commits with your `gpg` key,
meaning you need to have a key in your `gpg` setup, and then you can set that
key to be the default using the guidelines in [this
post](https://stackoverflow.com/questions/10161198/is-there-a-way-to-autosign-commits-in-git-with-a-gpg-key).
```

DOC contributing: trim lines and add notes on signoff

---

fairlearn/metrics/_metrics_engine.py
fairlearn/metrics/_skm_wrappers.py

Change `metric_by_group` and `make_group_metric` to understand `**kwargs`. This removes the need for lots of small wrapper functions

Use kwargs in metrics

---

requirements.txt
test/notebooks/test_notebooks.py
test/unit/reductions/grid_search/test_grid_search_regression.py

This was there previously but we thought it was fixed. Will need to validate with nightly builds to make sure it works.
Related to #265 but does not fix it :-(

Fix Windows notebook tests for  python 3.5 & 3.6 build by adding special case for BGL test case back

---

visualization/FairnessDashboard/src/WizardReport.tsx

hello!  The code that points to the copy for explaining what overprediction and underprediction are has a typo, check out the part of the example UCI notebook highlighted in purple:
Here's this diff for the test app in the project (the NaN is intentional in the setup for the test app, and some data is random):
Separately, this PR adds in a background color for the `presentationArea` to fix this in the test app.  This isn't a visible issue in Jupyter since the cell background is white, but this is what that same screen looks like in the test app without the background color:
Also, I assume to merge this we need to build the widget assets and check them in, but I didn't do any of that here yet.

Report: Fix copy bug on overprediction explanation in binary classifier

---

CHANGES.md
fairlearn/postprocessing/_threshold_optimizer.py
test/unit/postprocessing/test_threshold_optimization.py

This PR moves validations from `__init__` to `fit`, and adds an `estimator_` attribute to store the fitted estimator. Towards #222. Was a part of #282.

FIX ThresholdOptimizer: move validations to fit

---

CHANGES.md
fairlearn/metrics/_group_metric_set.py
test/unit/metrics/test_create_group_metric_set.py

Bring the argument names for `create_group_metric_set` into line with the Dashboard:
- `group_memberships` becomes `sensitive_features`
- `group_titles` becomes `sensitive_feature_names`
This change propagates through the tests as well

Rename arguments to create_group_metric_set

---

.github/auto-assign-reviewers-config.yml
.github/workflows/auto-assign-reviewers.yml

Adding a simple GitHub action to always assing me and Richard as reviewers. I'm planning to refine this in the future, ideally based on interest/specialization, but the current GitHub action doesn't have that functionality yet AFAICT. This PR also demonstrates a simple example of how to use GitHub actions in case we want to replace Azure Pipelines at some point.
addresses #285 

add auto-assign-reviewers action

---

fairlearn/reductions/_exponentiated_gradient/exponentiated_gradient.py

This is another step towards enabling us to plug them into Grid Search. 
This is related to the reductions refactoring outlined in https://github.com/fairlearn/fairlearn-proposals/issues/4

Store lambda vectors on the ExponentiatedGradient object

---

test/unit/postprocessing/test_smoke.py

This runs with prefit and without prefit estimator, so it should cover scenarios we previously missed.

add smoke tests for postprocessing

---

fairlearn/metrics/_group_metric_set.py
test/unit/metrics/test_create_group_metric_set.py

It appears that `LabelEncoder()` returns `numpy.int64` values. However, downstream users will need regular Python integers for JSON serialisation.

Fix for _create_group_metric_set()

---

requirements.txt
test/unit/postprocessing/test_plots.py

Closes #320 
Without using TkAgg our plotting tests would fail on MacOS. With 3.2.1 this isn't the case anymore, so we can happily remove the special case for MacOS in general, and apply a skip for MacOS with python 3.5 only. This means all future python versions as well as >=3.6 are tested without TkAgg specifically enabled.

Bump matplotlib to 3.2.1 and remove TkAgg workaround

---

CONTRIBUTING.md
README.md
fairlearn/__init__.py

A second attempt at releasing v0.4.5, including instructions on how to validate that the dashboard loads correctly.

Release v0.4.5

---

CHANGES.md
fairlearn/_input_validation.py
fairlearn/reductions/_exponentiated_gradient/_lagrangian.py
fairlearn/reductions/_exponentiated_gradient/exponentiated_gradient.py
fairlearn/reductions/_moments/bounded_group_loss.py
fairlearn/reductions/_moments/conditional_selection_rate.py

This fixes a `pandas` warning to the effect that
> The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning. 
Specify the `dtype` to be `float64` in all cases.

Set dtype for Series constructors

---

devops/PR-Gate.yml
devops/nightly-requirements-fixed.yml
devops/nightly.yml
devops/pypi-release.yml
devops/templates/all-tests-job-template.yml
devops/templates/fairlearn-installation-step-template.yml
devops/templates/pypi-deployment-stages-template.yml
devops/templates/test-run-step-template.yml

Refactor the job generation portions of the pipelines, so that more than the Python version is automatically expanded. The new system generates a job matrix which is a cartesian product over platforms, test runs and Python versions.
This is related to #371, but does not yet close that issue.

Improve pipeline job generation

---

CHANGES.md
fairlearn/_input_validation.py
fairlearn/reductions/_exponentiated_gradient/exponentiated_gradient.py
fairlearn/reductions/_grid_search/_grid_generator.py
fairlearn/reductions/_grid_search/grid_search.py
test/unit/reductions/grid_search/test_grid_search_arguments.py
test/unit/reductions/grid_search/utilities.py
test/unit/reductions/test_smoke.py

Closes #376 by removing the check for the number of sensitive features during input validation. To ensure that users still know that they shouldn't use GridSearch with many groups to avoid high-dimensional grids (which would be extremely costly to search thoroughly) we add a warning in the grid generation if `true_dim > 4` as an indication that the grid may get large. At the end of the day it should be up to the user to decide whether they want to explore it anyway, and this solution allows for that.

Enable GridSearch with more than 2 sensitive feature values

---

devops/templates/pip-freeze-to-artifact-steps-template.yml
setup.cfg

An update to `pip` changed the behaviour of `pip install .` resulting in a copy of the code being left in a `build` directory. This did not match the `per-file-ignores` set for flake8.
This changeset applies two fixes:
- Have `build` in the ignore list for flake8
- Ensure that `pip freeze` also reports the `pip` version in future

Fix flake8

---

.circleci/config.yml

I seem to have set it to read-only by accident, so need to replace the key. This time it's read/write.

regenerate CircleCI deploy key

---

fairlearn/reductions/_grid_search/_grid_generator.py
fairlearn/reductions/_grid_search/grid_search.py
test/unit/reductions/grid_search/test_grid_generator.py
test/unit/reductions/grid_search/test_grid_search_demographicparity.py

- Addition of grid offset in the grid generator. This is required for grid search algorithm when we  want the grid to be shifted by a lambda vector provided by the user.
Tests:
- Added unit test for generation of grid around user defined lambda vector.
- Added grid search with grid offset test case.

Add grid offset to grid generator for grid search

---

devops/nightly-requirements-fixed.yml

Get the Nightly-Fixed build green again by dropping Python 3.5. Since several of our dependencies are dropping Python 3.5 support, it does not make sense to keep it in our builds if giving trouble.

Fix for Nightly-Fixed

---

devops/templates/all-tests-job-template.yml

An incorrect match string for Production caused the final stage of our release pipeline to fail.

Fix incorrect ADO string

---

.circleci/config.yml

This is just so that we can get the landing page added in, planning to reenable shortly.

disable doc push temporarily

---

notebooks/Binary Classification with the UCI Credit-card Default Dataset.ipynb

An update to `scikit-learn` had required a workaround, but a subsequent release has removed this need.

Remove sklearn workaround for UCI Notebook

---

README.md
notebooks/ReadMe.md

Add a short ReadMe to the notebooks, explaining the need to keep the version aligned with whatever is `pip install`ed. This may help with things like #448 , but the real solution is to reduce our API breaks.

Add ReadMe about notebook versions

---

fairlearn/widget/js/package.json
visualization/FairnessDashboard/src/Controls/IntroTab.styles.ts
visualization/FairnessDashboard/src/WizardReport.styles.ts
visualization/FairnessDashboard/src/WizardReport.tsx

Note: Only the banner change is a required style change. 
The "welcome" tab fix is needed only if the user does `pip install .` 
There will be no new pypi release to support theme 
related PRs: 
https://github.com/fairlearn/fairlearn/pull/453
https://github.com/fairlearn/fairlearn/pull/445
Screenshots from my local widget testing:

[theme support] Minor styling changes in the intro tab and header banner

---

docs/_templates/index.html

The main call to action buttons on the website overlap at ~1000px width.
I didn't look at the build failures, as I'm assuming they are being discussed in https://github.com/fairlearn/fairlearn/issues/472.

Website: Fix buttons on desktop layout

---

docs/_templates/index.html

The website has two links in the top navbar, but right now they just scroll down to a section on that page that doesn't correspond to what the links say.
This PR removes those links, and replaces them with links the User Guide and API Docs, with the assumption that people trying to get a sense of the project can scroll to scan, and that we sholud enable people who land here knowing what they to get to it directly.  Right now the only way to get to the website outside of the two main call-to-action buttons is the User Guide link buried in the footer.
"Fairness in AI" scrolls to "How Fairlearn Works" and "About Fairlearn" scrolls to "Why Fairlearn?"

Website: Change top navbar to link to documentation

---

.circleci/config.yml
docs/conf.py
docs/quickstart.rst

The `quickstart.rst` document contains Python code which a user ought to be able to run. Use the `doctest` extension for Sphinx to enable this.

Convert quickstart to use doctest

---

.circleci/config.yml
docs/quickstart.rst
docs/user_guide/assessment.rst

The "metrics" portion of the Assessment user guide page was originally a notebook. Convert the embedded code snippets to `doctest` blocks, so that Sphinx can verify that they execute correctly.

Add doctest to metric section in userguide

---

.circleci/config.yml

Experiment with running the doctest build in parallel to the main documentation build. This is due to the growing execution time of our examples.

Run doctest build in parallel

---

docs/contributor_guide/contributing_example_notebooks.rst

This updates the page about contributing notebooks to include a short rubric for guiding critiques with five points:
1. Deployment context
2. For developers
3. Sociotechnical
4. Substantiated
5. Real harms
The intention is that this reflects the rough consensus about the team's aspirations from the meeting on 6/18 and discussion afterward.  While the [How to talk and write about fairness in AI](https://fairlearn.github.io/contributor_guide/how_to_talk_about_fairness.html) guide is awesome, in practice it's harder to refer to during a discussion.  So this minirubric is trying to be small enough that the team might practically use it within a meeting or discussion.

Documentation: Add microrubric for critiques

---

devops/templates/pip-freeze-to-artifact-steps-template.yml

There can be problems rerunning failed jobs due to build Artifacts being immutable. This is a particular issue for the 'freeze' artifacts, so append `System.JobAttempt` to the Artifact names, making the name for each retry distinct.

Improve job rerun

---

fairlearn/show_versions.py
test/unit/test_show_versions.py

Some minor changes to `show_versions()`:
- Have the python dependencies sorted alphabetically
- Add a smoke test of the `show_versions()` subroutine
The test is very much a smoke test; it verifies that the `show_versions()` subroutine does not throw any errors, and also that a few expected strings are present in the output. It does not verify that the version information itself has been fetched correctly.

Tweaks to show_versions()

---

docs/quickstart.rst
examples/notebooks/plot_grid_search_census.py

The latest Fairlearn version (v0.4.6) doesn't have the datasets module and users are hitting this issue frequently. To mitigate the problem this PR replaces the datasets module usage with the direct `fetch_openml` call until the next version is released.
closes #530 

remove datasets module usage until it is part of a released version

---

AUTHORS.md
docs/api_reference/index.rst

Fix double datasets entry in API Reference menu in the documentation.

Fix double datasets entry in docs

---

devops/nightly-requirements-fixed.yml

This makes the description of the Nightly Fixed build more accurate. Will also hopefully persuade ADO to start scheduling the build again.

Update comment in Nightly fixed

---

AUTHORS.md
README.md
docs/user_guide/further_resources.rst

Added a Resources section in README with the following-
- [fairlearn.github.io](https://fairlearn.github.io/)
- [FairLearn Whitepaper](https://www.microsoft.com/en-us/research/uploads/prod/2020/05/Fairlearn_whitepaper.pdf)
- [FairLearn Documentation](https://fairlearn.github.io/auto_examples/notebooks/index.html)
- [Fairlearn Examples](https://fairlearn.github.io/auto_examples/notebooks/index.html)
- [Building fairer AI Systems with Fairlearn on Channel 9](https://channel9.msdn.com/Shows/AI-Show/Building-fairer-AI-Systems-with-Fairlearn)
- [How to Test Models for Fairness with Fairlearn Deep-Dive on Channel 9](https://channel9.msdn.com/Shows/AI-Show/How-to-Test-Models-for-Fairness-with-Fairlearn-Deep-Dive)
- [Fairlearn in Practice at EY on Channel …

Added a Resources section

---

fairlearn/metrics/_disparities.py

Incorrectly referred to 'false negative rate.'

Fix description of EO

---

test/notebooks/test_notebooks.py

Check at the end of UCI notebook turned out to be rather fragile to changes in dependencies (either SciKit-Learn or LightGBM).

Fix notebook builds

---

requirements-dev.txt

Another fix for the notebook builds. Releases the upper bound on `papermill` which was causing trouble with the latest version of `nbconvert`.

Fix for notebook builds

---

fairlearn/metrics/_selection_rate.py
test/unit/metrics/test_selection_rate.py

Currently the squeeze call causes an issue for `y_pred` of length 1. Additionally, I've added a check to ensure it's not empty either.

fix selection_rate for y_pred of length 0 or 1

---

devops/other-ml-packages.yml
devops/templates/other-ml-job-template.yml
fairlearn/postprocessing/_threshold_optimizer.py
fairlearn/reductions/_moments/error_rate.py
fairlearn/reductions/_moments/utility_parity.py
test_othermlpackages/conda-tensorflow.yaml
test_othermlpackages/package_test_common.py
test_othermlpackages/test_tensorflow.py

Add TensorFlow to the `test_othermlpackages/` directory. Some product code modifications were required, since it appears that:
- `KerasClassifier.fit()` doesn't return `self`
- `KerasClassifier.predict()` returns an array of shape (n,1) and not of shape (n). This is important when subtracting from a pandas Series
Also tweak the pipeline so that changes to the `test_othermlpackages/` directory should trigger it as a gate.

Smoke tests for TensorFlow

---

test/unit/metrics/test_extra_metrics.py

Fill out some extra tests for `extra_metrics.py`, which test the TPR, FPR, TNR and FNR against calculations from the confusion matrix.

Extra tests for extra metrics

---

.circleci/config.yml
requirements-dev.txt

The documentation builds have a warning about the `pypandoc` package being missing. Add it to the `requirements-dev.txt` file, and also ensure that `pandoc` itself is installed on the machines which build the documentation.
Closes #589

Fix pypandoc warning in doc build

---

docs/contributor_guide/contributing_example_notebooks.rst
setup.cfg

Correct the developer setup command in the notebook contributing guide. Also highlight the need to prefix the filenames with `plot_` in order to have the outputs rendered on the webpage.
Make the flake8 suppressions for these files more targeted.

Improve notebook contributing guide

---

AUTHORS.md
CHANGES.md
fairlearn/reductions/_exponentiated_gradient/_lagrangian.py
fairlearn/reductions/_exponentiated_gradient/exponentiated_gradient.py
fairlearn/reductions/_grid_search/grid_search.py
test/unit/reductions/exponentiated_gradient/test_exponentiatedgradient_arguments.py
test/unit/reductions/grid_search/test_grid_search_arguments.py

Allow the user to supply sample_weight_key to better control the call to estimator.fit.
Fixes #580

Add sample_weight_name argument to Reductions

---

docs/contributor_guide/developer_call_notes/index.rst

Had overlooked adding the latest developer call notes to the index.
Closes #606 

Add developer call notes to index

---

docs/user_guide/assessment.rst
fairlearn/widget/fairness_dashboard.py

The public (not prefixed with underscore) attributes of the `FairlearnDashboard` class showed up in the documentation, and evidently the values from some use cases carried over, leading to a massive unintended data output. This PR fixes this problem by making the class attributes private. At the same time I took the liberty to convert the docs to numpydoc format.

Fix widgets docs by making class attributes private, convert to numpydoc

---

docs/quickstart.rst
docs/user_guide/assessment.rst
examples/plot_grid_search_census.py
notebooks/ReadMe.md

I would have liked to provide more details, such as the link to the migration guide for the version after 0.5.0. However, that would require knowing the version number at that point. I suspect it's 0.6.0 if we actually manage to remove the dashboard & add the matplotlib-based plots quickly. Linking forwards to a page that doesn't exist yet is kind of odd, though. Users of the dashboard can happily keep using it in 0.5.0 without any change, but once the version after that comes out the documentation/website will detail exactly how to migrate (because `raiwidgets` will actually be available) and replace the dashboard usage in quickstart, notebooks etc. where it's possible to replace the functionality (which will also address #608).

Add note about dashboard moving to raiwidgets after 0.5.0

---

fairlearn/metrics/_metric_frame.py
test/unit/metrics/test_metricframe_aggregates.py

Adding a default method of `between_groups` to `MetricFrame.difference()` and `MetricFrame.ratio()`. This had been previously discussed, but not implemented. Also make sure that the `method=` argument has documentation.

Set default of MetricFrame difference and ratio to be 'between_groups'

---

README.md
fairlearn/__init__.py

Some small changes:
- Bump version in `__init__.py` to `v0.5.1.dev0` (which is what our development trunk will be once v0.5.0 is out)
- Update the 'link to current version' in the main ReadMe to v0.5.0
I have left the remainder of the documentation links point to `master` for now, since they will break until v0.5.0 ships otherwise (I'm prepared to tolerate that one 'current' version at the top of the ReadMe, but not every link on the page).

Preparations for v0.5.0

---

fairlearn/metrics/_metric_frame.py
test/unit/metrics/test_metricframe_smoke.py

Metrics designed to slice and dice data into intersecting subgroups were somehow missing the case where only a single datum is passed in. Remedy this deployable oversight. Fixes #633

Fix metrics on single elements

---

docs/contributor_guide/developer_call_notes/2020_11_12.rst

Developer call ToC is messed up, likely because of choice of heading levels in latest notes.

Fixing formatting for developer call

---

docs/user_guide/assessment.rst
examples/plot_make_derived_metric.py
examples/plot_new_metrics.py
pyproject.toml

I had overlooked some comments on the previous PR for `make_derived_metric()`. This is to address those points.
The largest change is to the data preprocessing, which has been adjusted to avoid the problem of Data Leakage between the training and test sets (credit to @adrinjalali  for the actual `Pipeline` code). This fix has been ported to the other metrics example.

Updates for make_derived_metric

---

devops/code-coverage.yml
devops/nightly.yml

Two of the scheduled builds are consistently failing, due to issues fetching datasets from OpenML. Rerunning them manually works every time, so try changing the schedule for the affected builds.

Adjust build schedule

---

docs/conf.py

As noted by @hildeweerts  in #601 sorting members strictly alphabetically makes little sense. It turns out that there is an `autodoc` option to group things (e.g. properties, methods) together, so turn this on.

Change Autodoc sort order

---

docs/quickstart.rst
docs/user_guide/assessment.rst
docs/user_guide/mitigation.rst
test/unit/preprocessing/linear_dep_remover/test_sklearn_compat.py

Address build breaking issues:
- The latest version of `scikit-learn` was causing trouble with the tests for `CorrelationRemover` due to changes in the behaviour of the `check_sample_weights_invariance()` test. Since `CorrelationRemover` doesn't actually permit sample weights, remove this check from the list of checks run
- Something had changed how Pandas was printing out `DataFrame` objects, causing the expected output not to match in the docs. Force a precision to address this

Restore Green Builds

---

fairlearn/widget/_fairlearn_dashboard.py

The `flake8-blind-except` package had an update and has started objecting to some code in the dashboard. For now, address this by suppressing the check on the offending lines.

Fix flake8 break

---

CHANGES.md
README.md
docs/conf.py
docs/static_landing_page/index.html
fairlearn/__init__.py

Updates to the development trunk for v0.6.0 (these occur immediately after the tag/branch for v0.6.0:
- Bumps development version to v0.6.1.dev0
- Updates ReadMe to have link to v0.6.0
- Updates landing page to point to v0.6.0 docs by default
- Ensures that v0.6.0 docs are built

Release v0.6.0

---

devops/nightly-requirements-fixed.yml
devops/nightly.yml
devops/pypi-release-new.yml
devops/templates/limited-installation-job-template.yml

Add Python 3.9 to more of the builds we have. Unfortunately, this doesn't work with the 'Nightly Fixed' build.

More Python 3.9 builds

---

.circleci/config.yml
.github/ISSUE_TEMPLATE/bug_report.md
README.md
devops/PR-Gate.yml
devops/code-coverage.yml
devops/nightly-requirements-fixed.yml
devops/nightly.yml
devops/other-ml-packages.yml
docs/conf.py
docs/contributor_guide/contributing_example_notebooks.rst
docs/contributor_guide/development_process.rst
docs/contributor_guide/fairlearn_repository_overview.rst
docs/quickstart.rst
notebooks/ReadMe.md

Finally getting to this!
I did the following:
If you want to run these commands locally, copy from here:
```bash
git branch -m master <BRANCH>
git fetch origin
git branch -u origin/<BRANCH> <BRANCH>
```
This closes #477 
Outstanding:

Replace references to master branch with the new main branch

---

.circleci/config.yml
devops/PR-Gate.yml
devops/code-coverage.yml
devops/nightly-requirements-fixed.yml
devops/nightly.yml
devops/other-ml-packages.yml

Attempting to stop a bunch of scheduled builds kicking off on the (recently retired) `master` branch. It appears that since they still have the ADO build definitions referencing `master` the pipelines are still getting triggered. CircleCI may suffer from a similar problem. Adjust the branch name triggers for all of these.

Remove scheduled builds from old 'master' branch

---

test/unit/metrics/test_metricframe_smoke.py

The `MetricFrame` smoke tests didn't cover cases with `sample_params` (there are tests of `sample_params` but they check the internal methods, and not the API which users would invoke). Add a couple of tests to rectify this oversight.

Add missing MetricFrame tests

---

.circleci/config.yml

This is now necessary to ensure the CNAME file stays in the fairlearn.github.io repo.

add CNAME file command to website build

---

docs/api_reference/index.rst

Alphabetized packages in api docs.
This resolves https://github.com/fairlearn/fairlearn/issues/715
This is my first time contributing, let me know if I missed anything in the development flow.

Alphabetized packages in api docs

---

devops/pypi-release-new.yml
requirements-dev.txt

Having trouble with some pipelines:
- Documentation build was failing due to `pydata-sphinx-theme` releasing v0.6. Pin at 0.5.2 for now
- Had missed the path to `yarn` in the release pipeline

Build Pipeline fixes

---

devops/pypi-release-new.yml
requirements-dev.txt

Having trouble with some pipelines:
- Documentation build was failing due to `pydata-sphinx-theme` releasing v0.6. Pin at 0.5.2 for now
- Had missed the path to `yarn` in the release pipeline

Build Pipeline fixes (Cherry Pick #740)

---

README.md
docs/static_landing_page/index.html
fairlearn/__init__.py
requirements-dev.txt

Required updates to `main` for the `v0.6.1` release:
- Bump version in `__init__.py`
- Update links on the static landing page
Don't need to update the doc configuration this time (regex is flexible enough)

Update main for v0.6.1 Release

---

fairlearn/metrics/_metric_frame.py
test/unit/metrics/test_metricframe_process_features.py
test/unit/test_random_state.py

Related to https://github.com/fairlearn/fairlearn/issues/704
This PR fixes some warnings related to numpy dtypes.
Signed-off-by: Thomas J. Fan <thomasjpfan@gmail.com>

TST Fixes warnings for numpy dtype deprecations

---

fairlearn/reductions/__init__.py

Same as #747 but now with better branch name to avoid breaking `flake8` in a totally new way.

Fix flake8 warning in reductions/__init__.py

---

docs/conf.py
docs/quickstart.rst
examples/plot_quickstart_selection_rate.py
requirements-dev.txt

Our doc builds are taking a while, so it seemed like a good idea to replace the custom bokeh plot with a simpler matplotlib plot just like in #766 . Sadly, we are locked into all dependencies we ever had unless we're willing to go into older versions of Fairlearn, remove them from there, and then move the tag. Still, this simpler plotting code seemed like a step in the right direction.

Remove bokeh plot and replace with simple matplotlib plot

---

CHANGES.md
README.md
docs/contributor_guide/release.rst
docs/static_landing_page/index.html
fairlearn/__init__.py

Other than the adjustments in #774 this puts the version to `0.7.0.dev0` and adds the missing release instructions.
I expect the next release will require a new minor version since I have #766 out which should be completed shortly. We can certainly change that if this assumption turns out to be wrong, though.

Post-v0.6.2 release adjustments

---

docs/contributor_guide/release.rst

Small update to fix the link to the release page and adding a note not to complete the PR before the release is complete.

Update release instructions based on v0.6.2

---

docs/conf.py
requirements-dev.txt

Fixes #810 
Upon investigation, there is a newer, completely rewritten version of MathJax which is being used by Sphinx MathJax as well, the MathJax version 3. Thus it gave us `src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"` the latest version of the library in our HTML.
To accommodate this:
- Sphinx requires us to use `mathjax3_config` variable instead of `matjax_config` to set the configuration.
- Also there are some small changes in the config in terms of the syntax which were made using the [MathJax Configuration Converter](https://mathjax.github.io/MathJax-demos-web/convert-configuration/convert-configuration.html) to write the config in the new format.
**Before** 
**After**

Update mathjax_config to mathjax3_config

---

README.md

The migration guide was moved recently but README wasn't updated. Fixing that with this PR.

MNT fix README link to migration guide

---

docs/about/index.rst

Fixes the section title to match the vetted webpage header.
Signed-off-by: MiroDudik <mdudik@gmail.com>

Fix title of About Us doc section

---

examples/README.rst

The left example navbar is now autogenerated by sphinx-gallery so leaving this section  is causing duplicates in the navbar.

DOC Remove redundant toctree in gallery header (#872)

---

test/unit/reductions/exponentiated_gradient/test_exponentiatedgradient_smoke.py

This is currently failing in the `main` branch on Mac OS with Python 3.7 (https://dev.azure.com/responsibleai/fairlearn/_build/results?buildId=12387&view=logs&j=0a22f5d8-9f3e-5735-4672-5a55fb1a2abf&t=4a75d996-b002-586d-ec0d-145d497c0466)
```
>       assert disparity == pytest.approx(data["disp"], abs=_PRECISION)
E       assert 0.020000000000000018 == 0.019999 ± 1.0e-06
E        +  where 0.019999 ± 1.0e-06 = <function approx at 0x10f0f2d40>(0.019999, abs=1e-06)
E        +    where <function approx at 0x10f0f2d40> = pytest.approx
```
As @MiroDudik pointed out in #882 this should be fixed by adjusting the precision to `1e-5` instead of `1e-6`. Once this is merged we should cherry-pick it into #882 for the release v0.7.0

FIX adjust test precision to 1e-5

---

docs/user_guide/assessment.rst

This PR fixes #892 
Doc typo
- Replaced `conditional_features` to `control_features`.

DOC Typo on control features - fix

---

requirements-dev.txt

4.1.0 causes the logo to break #899. Once sphinx releases a new version we can check if it works and remove this pin again, or leave it and update in a controlled manner at a later point.

MNT pin sphinx at 4.0.3

---

docs/conf.py
requirements-dev.txt

The website build currently doesn't show `main`, only the released versions. This is because of a raised exception while parsing `conf.py`. Interestingly, this does not fail the entire build which is why it escaped detection. `gitpython` is struggling to recognize the repository locally, so instead we'll just run a `git` command to get all release versions.
Note that this will only be possible to validate once it's merged since the `main` version is based on the current `main` branch which has the `conf.py` that can't be parsed properly. I've validated locally that we get at least the same output as currently even if it doesn't fix the issue.

MNT remove gitpython, use git through subprocess instead

---

docs/conf.py
docs/contributor_guide/release.rst

#879 changed the behavior of the multiversion selection quite a bit, which resulted in `main` being excluded from the website. The root cause for that was that we use `gitpython` there but it doesn't work properly in that environment and therefore isn't able to pull in `refs` for the repo. As a follow-up I wrote #903 to use `git` directly (without `gitpython`), but as it turns out that's no better for the same reason. This PR reverts us back to the manual regex update until I manage to move us to a system that doesn't use `sphinx-multiversion`. Note that the CircleCI build will still exclude `main` if you check it here since it includes the current `main` branch rather than this current branch, and `main` will only get updated once we merge this.

MNT fix multiversion sphinx build

---

fairlearn/reductions/_moments/utility_parity.py
test_othermlpackages/test_xgboost.py

closes #910 
Fixing the `FutureWarning` from `pandas` by using `groupby` instead of the `level` arg in the `sum` aggregation.
Also fixing the `UserWarning` in `xgboost` by passing an additional arg as recommended by the warning.

FIX fix xgboost test

---

CITATION.cff

Add CITATION.cff file since there's a new feature to show how to cite papers/articles/books related to a repo: 
- https://twitter.com/natfriedman/status/1420122675813441540?s=20
- https://github.com/citation-file-format/citation-file-format
Importantly, this can be extended whenever we write a newer version/paper/whitepaper/article/etc.

DOC add citation cff file

---

devops/nightly-requirements-fixed.yml

closes #915 
Python version 3.9 dependency is removed from [nightly-requirements-fixed.yml](https://github.com/fairlearn/fairlearn/blob/main/devops/nightly-requirements-fixed.yml)

Removed py3.9 dependency from nightly-requirements

---

examples/plot_new_metrics.py

This pull request addresses one of the issues mentioned in #852. There also appear to be minor edits related to black formatting (changing single quotation marks to double quotation marks and changing spaces to tabs for multi-line commands).

Removing zero-division warnings

---

requirements-dev.txt

closes #899 by bumping the sphinx version to latest (v4.2.0)
Validated locally.

DOC bump sphinx to 4.2.0

---

fairlearn/metrics/_extra_metrics.py
test/unit/metrics/test_extra_metrics.py

fixes #963
This PR uses an integer minvalue instead of None in _get_labels_for_confusion_matrix, to fix the `TypeError: '<' not supported between instances of 'int' and 'NoneType'` issue

TST use int minvalue instead of None in _get_labels_for_confusion_matrix

---

docs/user_guide/installation_and_version_guide/v0.7.1.rst
fairlearn/preprocessing/_correlation_remover.py
test/unit/preprocessing/linear_dep_remover/test_sklearn_compat.py

fixes #964
Makes `CorrelationRemover` pass sklearn common tests, and include 2 tests which are going to fail as `xfail`. In the process, the estimator now exposes `n_features_in_` and `feature_names_in_` via calling `_validate_data`.
It's also formatting the two files with `black`.

ENH make CorrelationRemover expose n_features_in_ and feature_names_in_

---

docs/user_guide/datasets.rst
docs/user_guide/index.rst

Changes include slight grammatical adjustments to the datasets rst file and addition of the datasets section to the user guide index.

Final edits to boston housing documentation

---

docs/conf.py
fairlearn/reductions/_moments/utility_parity.py

Fixing a few doc build warnings including
```
loading intersphinx inventory from https://github.com/GPflow/tensorflow-intersphinx/raw/master/tf2_py_objects.inv...
intersphinx inventory has moved: https://github.com/GPflow/tensorflow-intersphinx/raw/master/tf2_py_objects.inv -> https://raw.githubusercontent.com/GPflow/tensorflow-intersphinx/master/tf2_py_objects.inv
```
and
```
/fairlearn/reductions/_moments/utility_parity.py:docstring of fairlearn.reductions._moments.utility_parity.TruePositiveRateParity:26: WARNING: py:meth reference target not found: signed_weights
```
as well as a few links that didn't render due to missing trailing underscores and inconsistent line-wrap.

MNT fix doc build warnings

---

docs/user_guide/datasets/acs_income.rst
docs/user_guide/datasets/adult_data.rst
docs/user_guide/datasets/boston_housing_data.rst
docs/user_guide/datasets/index.rst
docs/user_guide/index.rst
docs/user_guide/installation_and_version_guide/v0.7.1.rst
fairlearn/datasets/__init__.py
fairlearn/datasets/_fetch_acs_income.py
fairlearn/datasets/_fetch_acsincome.py
fairlearn/datasets/_fetch_adult.py
fairlearn/datasets/_fetch_bank_marketing.py
fairlearn/datasets/_fetch_boston.py

This PR introduces documentation describing the ACSIncome dataset, which is 1 of 5 datasets created and published by Ding et al. (2021) [link](https://arxiv.org/pdf/2108.04884.pdf). The documentation summarizes the features and target variable of the dataset. It also reorganizes the documentation files in preparation for adding the other datasets from Ding et al. However, in the spirit of [Lutz' Law](https://twitter.com/romanlutz13/status/1451289545627086849), the other datasets will be left for future PRs.
Looking forward to your comments. Thanks in advance for reviewing!

DOC: ACSIncome Documentation

---

fairlearn/metrics/_metric_frame.py
test/unit/metrics/test_metricframe_process_features.py

An update to `pandas` (with Python 3.9) changed an error message from `DataFrame.from_dict()`. One of our tests was unnecessarily examining this error message, and hence started failing. Remove this check, and change the message in our exception.
Closes #1012

Fix test in MetricFrame

---

examples/plot_quickstart.py

Before:
- Fairlearn quickstart page showed both recall and true positive rate, which are the same metrics, on its plots.
Now:
- Replaced true positive rate with true negative rate on the plots.

Fixed quickstart page

---

test_othermlpackages/conda-tensorflow.yaml
test_othermlpackages/conda-xgboost.yaml

Fix a couple of issues with our tests with other ML packages:
- The latest version of `pandas` objects to how `xgboost` was using it (specifically `FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.`). Temporarily exclude this version of `pandas` with an upper bound
- It appears that `conda-forge` had the latest `scikeras` but not the latest `tensorflow` to match it. Switch to installing both from `pip`
Have filed #1015 as a reminder to watch `xgboost` for an update to be compatible with the latest `pandas`.

Fix other ML packages tests

---

devops/PR-Gate.yml
devops/nightly-requirements-fixed.yml
devops/nightly.yml
devops/pypi-release-new.yml
devops/templates/all-tests-job-template.yml

The Windows image we have been using in our build is scheduled for retirement. See [this issue](https://github.com/actions/virtual-environments/issues/4312) for more details. Change to use the `windows-latest` image.

Update Windows image

---

.circleci/config.yml

Fixing the publish stage of the doc build, which has been broken since #1046 .
The new image lacked `npm`, so install it via `apt-get`. When `npm` itself is run, it also needs to be superuser.

Doc build bug fix

---

fairlearn/datasets/_fetch_acs_income.py
fairlearn/datasets/_fetch_adult.py
fairlearn/datasets/_fetch_boston.py
fairlearn/metrics/_disparities.py
fairlearn/metrics/_extra_metrics.py
fairlearn/metrics/_metric_frame.py
fairlearn/metrics/_selection_rate.py
fairlearn/postprocessing/_interpolated_thresholder.py
fairlearn/postprocessing/_threshold_operation.py
fairlearn/postprocessing/_threshold_optimizer.py
fairlearn/preprocessing/_correlation_remover.py
fairlearn/reductions/_exponentiated_gradient/exponentiated_gradient.py
fairlearn/reductions/_grid_search/grid_search.py
fairlearn/reductions/_moments/bounded_group_loss.py
fairlearn/reductions/_moments/error_rate.py
fairlearn/reductions/_moments/moment.py
fairlearn/reductions/_moments/utility_parity.py

This PR addresses issue #730 by adding links to the user guide in many of the API function and class definitions. For some of the classes and functions, like those referenced in the preprocessing, postprocessing, and reductions modules, the corresponding user guide documentation has not been written yet (but has placeholders). In those cases, I added a placeholder reference to the appropriate section in anticipation of that documentation being added someday. If a function or class didn't have user guide representation, either written or planned, I did not add a reference. Please let me know if I should go back and add references for everything by estimating where the user guide documentation would go. Tagging @romanlutz and @hildeweerts for their reviews!
N/A

Adding user guide documentation to API

---

.git-blame-ignore-revs

Following up on https://github.com/fairlearn/fairlearn/pull/1083, this PR adds that commit to `.git-blame-ignore-revs`. This should automatically fix the blame on github, and locally it can be enabled by:
git config blame.ignoreRevsFile .git-blame-ignore-revs
cc @romanlutz @hildeweerts @riedgar-ms for an easy review.

MNT add lint PR to git-blame-ignore-revs

---

docs/_static/versions.json
docs/conf.py

It seems the documentation [here](https://pydata-sphinx-theme.readthedocs.io/en/latest/user_guide/configuring.html#add-a-dropdown-to-switch-between-docs-versions) might be misleading and the links shouldn't have the `index.html` at the end.

FIX fix multiversion links

---

fairlearn/metrics/_metric_frame.py
test/unit/metrics/test_metricframe_aggregates.py

Work related to #999 uncovered a zero-divide bug when `MetricFrame` was computing ratios. Annoyingly, the required fix was present in half the routine, but not the other.

FIX Zero Divide fix for MetricFrame

---

docs/user_guide/assessment.rst
fairlearn/metrics/_annotated_metric_function.py
fairlearn/metrics/_metric_frame.py

The `AnnotatedMetricFunction` constructor argument `positional_argument_names` was misspelled. Since this is not used directly by users, there are no documentation or test changes.
However, while fixing this issue, discovered that the doc build was failing due to pandas 'print' output changing. So fix that as well in `assessment.rst`.
At this point I decided to install `mypy` as well, and fix some of the warnings generated for `MetricFrame`.

[BugFix] Small metric fixes

---

README.rst

README link broke after PR #1123 for splitting assessment docs.
@riedgar-ms 
N/A

[DOC] Fix README link to assessment docs

---

docs/contributor_guide/contributing_documentation.rst

Fixes #1056. Adds explanation for BibTeX citations to the [Contributor Guide](https://fairlearn.org/main/contributor_guide/contributing_documentation.html).
Built documentation locally and verified.

DOC Add explanation for BibTeX citations

---

docs/_static/versions.json
docs/conf.py

this should resolve #1150 
@adrinjalali: I wasn't sure why 0.9.0 in `versions.json` was called `"v0.9.0"` instead of `"0.9.0"` like the others so I assumed this was a typo - let me know if I'm missing something here :)

[DOC] fix bad source links

---

requirements-dev.txt

Linting failing with latest `flake8` v6.0.0. See:
https://github.com/PyCQA/flake8/issues/1760

CI Set Upper bound on flake8 version in CI

---

docs/quickstart.rst
docs/user_guide/mitigation/adversarial.rst
docs/user_guide/mitigation/preprocessing.rst
examples/plot_correlationremover_before_after.py
examples/plot_grid_search_census.py
examples/plot_make_derived_metric.py
examples/plot_new_metrics.py
examples/plot_plotting_metrics_with_error.py
examples/plot_quickstart.py
fairlearn/datasets/_fetch_acs_income.py
fairlearn/datasets/_fetch_adult.py
fairlearn/datasets/_fetch_bank_marketing.py
fairlearn/datasets/_fetch_boston.py
fairlearn/datasets/_fetch_diabetes_hospital.py
requirements-dev.txt
test/unit/adversarial/test_preprocessing.py
test/unit/metrics/test_generated_metrics.py
test/unit/reductions/grid_search/test_grid_search_demographicparity.py
test/unit/test_random_state.py
test_othermlpackages/adversarial_fairness.py
test_othermlpackages/package_test_common.py

Signed-off-by: Miro Dudik <mdudik@gmail.com>
Three sklearn 1.2 related issues are being fixed:
* A typo in our test scripts: mismatched feature names between fit and predict. This was previously FutureWarning in sklearn, but with sklearn 1.2 it is now an error.
* Default behavior of log loss in sklearn 1.2 changes, affecting the evaluation of log loss in derived metrics. The default only kicks in when prediction=0 and truth=1 or vice versa, so the tests are adjusted to avoid this case (and give the log loss value equal to the previous default behavior).
* Warnings issued by fetch_openml when `parser` keyword argument is not present.
Additionally:
* autopep8 version is being kept lower to keep our linting scripts working

BUG fix bugs in tests that surfaced with sklearn 1.2 and autopep8 2.0.1

---

fairlearn/reductions/_moments/error_rate.py

`ErrorRate` is not the same as `ErrorRateParity`, but the link kind of indicates that it is so it's best to remove it. We don't currently have a user guide for `ErrorRate`, but we should add one.

DOC remove misleading link to error rate parity user guide

---

docs/user_guide/assessment/common_fairness_metrics.rst

Addresses Issue #1154 
https://github.com/fairlearn/fairlearn/issues/1154
The old line used "equal opportunity" in the definition of equal opportunity which was a bit confusing.
It also drops the concepts of groups, which the previous section on Equalised Odds was using throughout.
I've made a suggested change that addresses this issue.
@hildeweerts @romanlutz 
- [x ] no new tests required
- [x ] user guide added or updated

Amendment to Equal Opportunity Definition

---

.gitignore
examples/plot_quickstart.py

Fixes #1192 
Don't generate `filename.png` for doc build

DOC: Don't generate filename.png for doc build

---

.github/workflows/nightly.yml
requirements.txt
scripts/install_requirements.py
test_othermlpackages/conda-xgboost.yaml
test_othermlpackages/test_xgboost.py

The xgboost tests are currently failing because `use_label_encoder` is deprecated. From v1.7.0 onwards it should be omitted.
While I check the requirements I also found that we had several packages with minimum versions that are apparently not supported by Python 3.8, so I bumped them.

[MNT] Fix failing xgboost tests in the otherml test pipeline

---

docs/contributor_guide/contributing_documentation.rst
docs/contributor_guide/release.rst

closes #1098 
We moved away from sphinx multiversion some time ago. This PR removes the last remnants of sphinx multiversion from our docs. I don't think the release process needs to be adjusted, though. From what I can tell, it is smart enough to update the older versions based on release branches.
contrib guide adjusted

DOC remove multiversion remnants

---

codecov.yml

As suggested (https://github.com/codecov/codecov-action/issues/837#issuecomment-1453877750), this PR adds the codecov token to our config so that the codecov uploads become more reliable (they're very annoying).
Note that we can't put the token as a secret since secrets are not exposed to PRs from forks.
This does not add a security issue since people can upload coverage to the codecov anyway.

MNT add codecov token

---

README.rst

I fixed the broken link to the example notebooks section under the main readME 
Closes #1221

Fixed broken notebooks link in main readME

---

docs/about/index.rst

Adds citation of the preprint of the new Fairlearn paper, standard arXiv style.
Closes #1251
Standard ACM reference would render like this, which looks perfectly fine to me:

DOC update citation

---

test_othermlpackages/conda-tensorflow.yaml

Related to #1254 
Numpy added errors for using `typeDict` and TF has not updated their code, so our TF tests need to pin numpy at a working version. According to https://stackoverflow.com/questions/74852225/attributeerror-module-numpy-has-no-attribute-typedict 1.21 is such a working version, but the gates will show...

MNT use older numpy version in tensorflow tests to allow tensorflow to run without deprecation errors

---

requirements-dev.txt
test_othermlpackages/conda-lightgbm.yaml

Related to #1254 
This PR fixes an incompatibility between lightgbm and numpy in the latest versions (4.0.0 and 1.25.1, respectively) by prohibiting lightgbm to upgrade to 4.0.0
I validated locally that it fixes the problem. Here's the bug on lightgbm for reference https://github.com/microsoft/LightGBM/issues/5990

MNT Fix lightgbm test

---

fairlearn/postprocessing/_threshold_optimizer.py

In postprocessing code, we're using `type(object) == Type` instead of `isinstance(object, Type)` which now causes flake8 issues.

MNT fix flake8 issues due to string comparison by using isinstance

---

.github/workflows/linting.yml
.pre-commit-config.yaml
fairlearn/metrics/_metric_frame.py
fairlearn/postprocessing/_interpolated_thresholder.py
fairlearn/postprocessing/_threshold_optimizer.py
fairlearn/reductions/_exponentiated_gradient/exponentiated_gradient.py
requirements-dev.txt

Updating linter versions, and flake8 has moved to github. Will do another PR to move to `ruff` instead for `isort` and `flake8`.

MNT update linter versions

---

requirements.txt

Turns out that we actually need SciKit-Learn 1.2.1 or later, due to a bug in the parsing. Related to #1168

MNT Bump SciKit-Learn patch

---

test_othermlpackages/conda-lightgbm.yaml
test_othermlpackages/conda-pytorch.yaml
test_othermlpackages/conda-tensorflow.yaml
test_othermlpackages/conda-xgboost.yaml

Bump the version of Python used by the Conda files in `test_othermlpackages`. For all except TensorFlow, this involves going to Python 3.11; Tensorflow only seems to work with Python 3.10.

Bump Python for OtherML packages

---

.github/workflows/build-test.yml
fairlearn/metrics/_disaggregated_result.py
fairlearn/metrics/_metric_frame.py
pyproject.toml
requirements.txt
setup.py

The recent `pandas` 2.1 release has simultaneously introduced a new `DataFrame.map()` API, and deprecated the `DataFrame.applymap()` API which we use in `MetricFrame`. Since our builds fail on warnings, this left us with a conundrum. This PR (temporarily) solves this by changing the `DataFrame.applymap()` calls to a nested `DataFrame.apply()` pattern. This is not particularly great, but this should not be being used in performance-critical portions of `MetricFrame` and can suffice until we decide to require `pandas` be at least version 2.1.
Also make sure that Python 3.7 is fully excised and add 3.11 to the regular builds and setup.
Issue #1299 exists to track the need to tidy all of this up once we drop `pandas` v2.0 support.

MNT Fixing pandas

---

.github/workflows/build-test.yml
.github/workflows/test-all-deps.yml
.github/workflows/test-other-ml.yml
test_othermlpackages/conda-lightgbm.yaml

Taking another swing at getting our builds to Green. There are two changes:
- I saw errors from CodeCov about 'too many uploads for commit.' Since we don't have different code paths based on Python version, I've tweaked the CodeCov step so that it only runs for Python 3.11
- The `test_otherml` directory was still getting warnings. Since those dependencies are not entirely under our control, my solution is to override the `pyproject.toml` and "Treat Warnings as Warnings." I know that this is not ideal, but short of unpicking the exact combination of packages which get installed, it's probably the most robust solution

MNT Further build fixes

---

requirements-dev.txt

Yet another hack at our Nightly build. I'm not sure why `pytest-mpl` had a lower bound, but it was quite old. Remove it entirely, in the hopes of killing off another warning-as-error (which was actually coming from what appears to be the expected `pytest-mpl` workflow).
The errors being generated were of the form:
```
FAILED test/unit/postprocessing/test_plots.py::TestPlots::test_plot_equalized_odds_ex1 - pytest.PytestReturnNotNoneWarning: Expected None, but test/unit/postprocessing/test_plots.py::TestPlots::test_plot_equalized_odds_ex1 returned <Figure size 640x480 with 1 Axes>, which will be an error in a future version of pytest.  Did you mean to use assert instead of return?
```
I suspect that a later version of `pytest-mpl` 'knows' how to suppress this (since the …

MNT Release pytest-mpl bound

---

.github/workflows/build-test.yml
.github/workflows/nightly.yml
.github/workflows/test-minimal-deps.yml

I'm seeing more whining from CodeCov about too many results for a single commit. Extend the 'single version of Python' filter to the `minimal-deps` portion of the build.

MNT CodeCov Fixes

---

.circleci/config.yml
.circleci/push_doc.sh

Our documentation build is failing while copying files around for `fairlearn.github.io`. Trying to fix this problem (related to #1280).

DOC Attempting to fix doc push

---

docs/_static/versions.json
docs/static_landing_page/js/landing_page.js
docs/user_guide/installation_and_version_guide/v0.10.0.rst
docs/user_guide/installation_and_version_guide/v0.11.0.rst
fairlearn/__init__.py

I pushed through the v11 release and am at the last step. I followed the steps in the release guide:
1. Update the version in __init__.py to 0.11.0.dev0
2. Update the version in docs/static_landing_page/js/landing_page.js so that all the links point to the new release
4. Update the docs/_static/versions.json file
6. Create a new file 0.11.0.rst in docs/user_guide/installation_and_version_guide
@riedgar-ms, please take a look and let me know if everything looks correct!

Setting up the landing page for version release and prep for v0.11.0

---

requirements.txt

Fixes https://github.com/fairlearn/fairlearn/issues/1334

MNT add pyarrow dependency

---

docs/user_guide/assessment/common_fairness_metrics.rst

I added a missing parenthesis in the Equalized odds latex formula.
- [ x] no new tests required
- [x ] no documentation changes needed

Fixed missing parenthesis in the Equalized odds formula

---

examples/plot_plotting_metrics_with_error.py

From version >1.2 of scikit-learn `sparse` was changed to `sparse_output`

MNT update sparse to sparse_output

---

docs/user_guide/installation_and_version_guide/v0.10.0.rst

Deletes the empty note block in the version guide of v0.10.0 that gives an [error](https://app.circleci.com/pipelines/github/fairlearn/fairlearn/3962/workflows/4b5df195-d6a3-4132-bdfb-9f0ae746556f/jobs/7888/parallel-runs/0/steps/0-108?invite=true#step-108-64504_158) in the doc build.

MNT delete trailing note in version guide

---

fairlearn/metrics/_disaggregated_result.py
requirements.txt
test/unit/reductions/grid_search/test_grid_generator.py
test_othermlpackages/conda-lightgbm.yaml

Various tweaks to fix the builds:
- Temporary upper bound on `scikit-learn`. Issue #1350 for tracking. A full fix will be required in due course
- Tweaks a couple of the grid generator tests to avoid warnings from `pandas`
- Adjust `_disaggregated_result.py` to cope with recently introduced (and deprecated) argument from `pandas`
Both of the `pandas` changes should fall under #1299

MNT Build fixes

---

requirements.txt
test/unit/metrics/test_metricframe_missing.py
test/unit/metrics/test_metricframe_smoke.py

We had temporarily added an upper bound on SciKit-Learn since there were issues with some of our tests. Remove the bound and address the test failures.
Closes #1350

Release upper bound on scikit-learn

---

.github/workflows/build-test.yml
.github/workflows/linting.yml
.github/workflows/nightly.yml
.github/workflows/release-wheel.yml
.github/workflows/test-all-deps.yml
.github/workflows/test-minimal-deps.yml
.github/workflows/test-other-ml.yml
test/unit/adversarial/test_adversarial_mitigation.py
test_othermlpackages/conda-tensorflow.yaml

Address a number of issues in the builds
- The `macos-latest` runner is now ARM based and doesn't have older Python versions. Stick with `macos-12` for now
- Fix a variable name which had started upsetting `flake8`
- Upper bound on `scikeras` to at least get the TensorFlow test running again
- Update various GitHub Action versions

[Build] Fix issues

---

docs/contributor_guide/contributing_documentation.rst
docs/user_guide/assessment/common_fairness_metrics.rst

This PR fixes three typos in the documentation. 
The first two remove an extra space after the :`code:` markup that failed to render a code snippet block in the documentation contribution guide (59ba2ed1a0d48dc9648a076f104b0c73a0c707a5). The third is a text typo in the common metrics user guide (e06df00a16a3ef368adcbf1fef0aba36233227bd). 
@adrinjalali

DOC Fix typos in the documentation

---

requirements-dev.txt

I don't see any errors with the latest pytest release. So removing the pin.
cc @riedgar-ms @romanlutz

MNT unpin pytest

---

docs/user_guide/mitigation/adversarial.rst

This (tiniest) PR changes the remaining `OneHotEncoder.sparse` to `sparse_output`. In all the other places it has been updated already. 
@adrinjalali this came up while we were working on https://github.com/fairlearn/fairlearn/issues/1373.

DOC change OneHotEncoder.sparse to sparse_output

---

.github/workflows/build-test.yml
.github/workflows/test-other-ml.yml
docs/quickstart.rst
docs/user_guide/assessment/advanced_metricframe.rst
docs/user_guide/assessment/custom_fairness_metrics.rst
docs/user_guide/assessment/intersecting_groups.rst
docs/user_guide/assessment/saving_loading_metricframe.rst
docs/user_guide/mitigation/postprocessing.rst
docs/user_guide/mitigation/reductions.rst
fairlearn/reductions/_exponentiated_gradient/_lagrangian.py
fairlearn/reductions/_exponentiated_gradient/exponentiated_gradient.py
pyproject.toml
test_othermlpackages/conda-lightgbm.yaml
test_othermlpackages/conda-tensorflow.yaml

CI won't pass for this PR. I am proposing it here as a summary of the work done today, mostly by many different tries and builds in #1385. 
This PR adds the `numpy2.0.0` API guidelines in the `ruff` linter and fixes the found issues in 1b5f0bf6aeef770a4865a99002d8642c87b7eaba.
After the update, CI failed for two packages, `lightgbm` and `tensorflow`. I tried many different combinations to solve the problems in both configurations, and it seems for `lightgbm` limiting the version helps [cabcd69](https://github.com/fairlearn/fairlearn/pull/1387/commits/cabcd69094aa017517b9cab56f540233d05fc5ca). For `tensorflow` I am not able to find a consistent solution. 
Any ideas for a solution for this? Is it better maybe not to merge these changes, and to keep the version in the range as specified in …

MNT Update code to fit the new numpy2.0.0 API

---

examples/plot_credit_loan_decisions.py
fairlearn/adversarial/_adversarial_mitigation.py
requirements.txt
test/unit/adversarial/test_adversarial_mitigation.py
test_othermlpackages/test_lightgbm.py

This PR addresses issue #1381.
Additionally, the new scikit-learn estimator checks are enabled for both `AdversarialFairnessClassifier` and `AdversarialFairnessRegressor`. As a result many checks are failing and they are added under the `xfail` flag. They would be addressed individually in the future.
@adrinjalali

FIX Add classes_ attribute to AdversarialFairnessClassifier

---

.circleci/config.yml
fairlearn/adversarial/_preprocessor.py

This PR follows up on the discussion in #703, specifically [this comment](https://github.com/fairlearn/fairlearn/issues/703#issuecomment-2200224570), in hopes to have less CI failures when OpenML datasets aren't available to download in order to run the examples.
More information about the CircleCI process [here](https://circleci.com/docs/caching/).
Inspiration taken from [scikit-learn](https://github.com/scikit-learn/scikit-learn/blob/main/.circleci/config.yml#L34-L49).

MNT Add caching for branches in the doc and doctest CircleCI builds

---

fairlearn/adversarial/_adversarial_mitigation.py
fairlearn/preprocessing/_correlation_remover.py

This PR fixes all failing estimator checks related to `check_parameters_default_constructible`. It also fixes #1368.
@adrinjalali

FIX all estimator checks related to: check_parameters_default_constructible

---

fairlearn/adversarial/_adversarial_mitigation.py
test_othermlpackages/adversarial_fairness.py

This PR fixes all failing estimator checks related to: `check_supervised_y_no_nan`. The custom `check_X` in `_adversarial_mitigation` is not necessary any more, so the API docs are accordingly generated. By inheriting from `sklearn.base.BaseEstimator`, we also inherit `BaseEstimator._validate_data` which contains the functionality.
The way the values are validated can be possibly further revised, but for the sake of a shorter PR and making progress on the xfailed estimator tests I'm proposing these changes now.
@adrinjalali

FIX all estimator checks related to: check_supervised_y_no_nan

---

docs/user_guide/installation_and_version_guide/v0.11.0.rst
fairlearn/adversarial/_adversarial_mitigation.py
fairlearn/adversarial/_preprocessor.py
test/unit/adversarial/test_preprocessing.py

This PR is not big, but it adds multiple non-trivial changes.
- As proposed in #1395, the `check_classifiers_train` always expect a `numpy.array`, while until now the input type was preserved for `list`, `Dataframe` and `Series`. This is now removed, and while those inputs are still allowed, the output will always be a `numpy.array`.
- I removed `_AdversarialFairness.decision_function` of not upholding the expected contract with `_AdversarialFairness.predict` that the estimator checks demand. It's output is preserved in `_raw_predict`, which someone could use if necessary, and it is called by `predict`.
- Because of the lack of a decision function, the `check_regressors_no_decision_function` passes now too so it is removed from under the xfail tag.
- Some minor refactoring on top of those …

FIX failing estimator checks: "check_classifiers_train" and "check_regressors_no_decision_function"

---

fairlearn/adversarial/_adversarial_mitigation.py
fairlearn/adversarial/_constants.py
fairlearn/adversarial/_preprocessor.py
test/unit/adversarial/helper.py
test/unit/adversarial/test_adversarial_mitigation.py

This PR fixes the errors raised by these three scikit-learn estimator checks:
- `check_estimators_pickle`
- `check_estimators_overwrite_params`
- `check_classifiers_classes`
@adrinjalali

MNT Fix errors caused by three estimator checks

---

test_othermlpackages/conda-pytorch.yaml

It turns out torch doesn't support 3.13 yet and that was the issue.

MNT fix version constraint for torch

---

.github/workflows/release-wheel.yml

This PR updates the release wheel. 
Unfortunately, the `JesseTG/rm@v1.0.3` action hasn't been maintained in a long time and it cannot be updated straightforward, but [we could reference the hash of a merged commit as suggested in this issue](https://github.com/JesseTG/rm/issues/15#issuecomment-2328257081). That commit makes the necessary changes to move away from `node 16` which is deprecated. Anyone that has a replacement for it? 
@fairlearn/fairlearn-maintainers @adrinjalali

Update release wheel (deprecated actions)

---

test/unit/utils/test_input_manipulations.py

The changes only concern rewriting the unit tests for input manipulation utils, namely:
- Used `np.testing.assert_equal_array` for array comparisons.
- Used pytest parametrization for running multiple test cases on the same function behaviour.
- Used pytest raises's `match` argument to assert equal expected error message.
No existing tests were removed/modified.
This a small PR suggestion whose purpose is mainly to get myself used to the dev process on `fairlearn` before potentially tackling more useful issues.
- [] user guide added or updated

chore: revamp input manipulation unit tests

---

docs/user_guide/assessment/perform_fairness_assessment.rst
fairlearn/metrics/_disaggregated_result.py
fairlearn/metrics/_metric_frame.py
test/unit/metrics/test_metricframe_nonscalar.py

I simplified the `_none_to_nan` method, which made it also work for dataframes and series out of the box, and added a couple of unit tests.
I also removed a hardcoded `"object" ` dtype in `apply_grouping` which was most of the times fixed under the hood with the pandas' `.map`.
I had to fix a couple of expectations in the doctest.
(sorry for the spam, I'm still slowly reading through the codebase, and making small (and hopefully safe) suggestions in the meanwhile :sweat_smile: )

refactor: simplify none to na

---

fairlearn/metrics/_disaggregated_result.py
fairlearn/metrics/_fairness_metrics.py
fairlearn/metrics/_metric_frame.py
test/unit/metrics/test_fairness_metrics.py

Hello ! This small PR has two commits:
- The first commit is the main one: it fixes the `agg` argument's validation in the two `equalized odds` functions, by raising instead of returning an exception. I added a couple of unit tests to cover that branch.
- The second commit is less important, it's just a follow-up on [my previous PR,](https://github.com/fairlearn/fairlearn/pull/1432) where I missed a couple of literals :sweat_smile:

Fix equalized odds exceptions

---

fairlearn/metrics/_metric_frame.py
test/unit/metrics/test_metricframe_bootstrap.py

Hi again !  this small MR aims to improve the user experience a bit by hiding the metric frames internals more.
Basically, when the user tries to access a confidence-intervals-related attribute of a `MetricFrame` object which was not initialized with the confidence-intervals-related parameters (`n_boot` , `ci_quantiles`), she gets a `KeyError` exposing the internal `result_cache` object, which imho is not user-friendly (example in the figure below).
If you agree with these changes, please let me know, I'll go ahead and add associated unit tests :pray:

Raise user-friendly error on missing ci parameters

---

fairlearn/metrics/_annotated_metric_function.py
fairlearn/metrics/_bootstrap.py
fairlearn/metrics/_disaggregated_result.py
fairlearn/metrics/_group_feature.py
fairlearn/metrics/_make_derived_metric.py
fairlearn/metrics/_metric_frame.py
fairlearn/metrics/_plot_model_comparison.py
fairlearn/metrics/_plotter.py

Fixed some type hints in the metrics package.

fix: type hints within metrics

---

fairlearn/metrics/_disaggregated_result.py
test/unit/metrics/test_disaggregated_result.py

- Simplified code complexity by using pandas built-in methods.
- Refactored the common logic in initializing the `overall` and `by_group`  inside `.create`.
- Added unit tests to cover the latter.
There are some linting changes to the doc that could be merged as part of this [other PR](https://github.com/fairlearn/fairlearn/pull/1434)

refactor: simplify disaggregated result

---

fairlearn/datasets/_fetch_adult.py
test/unit/preprocessing/linear_dep_remover/test_correlation_remover_efficiency.py

Hi @TamaraAtanasoska 
This is my first attempt to address #1419. Even though this PR only covers the `CorrelationRemover` and the `adult` dataset, the test function itself (and the `FairnessComparisonData` class) is agnostic to both the mitigation method and the dataset it is applied to, which can hopefully make it easily extendible.

test: correlation remover enhances fairness metrics

---

docs/user_guide/mitigation/postprocessing.rst
fairlearn/postprocessing/_plotting.py
fairlearn/postprocessing/_threshold_optimizer.py
fairlearn/postprocessing/_tradeoff_curve_utilities.py

Hello, this PR is mainly about the user guide for the `ThresholdOptimizer` with constraints other than equalized-odds. It has two parts:
- The first one consists of small fixes to the docs (commented out code line, extra space, missing double-quotation...).
- The second one is more interesting: I added the curve of the objective weighted by the size of the groups to the plot so that the quantity we are maximizing is displayed, and the user can understand why the solution's vertical line happen to be at that exact spot.
> To ensure that the fairness constraint is upheld [ThresholdOptimizer](https://fairlearn.org/v0.11/api_reference/generated/fairlearn.postprocessing.ThresholdOptimizer.html#fairlearn.postprocessing.ThresholdOptimizer) simultaneously walks along all the curves while …

Plot thresold optimizer weighted objective

---

fairlearn/preprocessing/_correlation_remover.py
test/unit/preprocessing/linear_dep_remover/test_sklearn_compat.py

This PR removes resolves the failing estimator checks in the `Correlation Remover`.
The class could use some additional refactoring, added to my list for the future.
ping @adrinjalali this is what I mentioned in https://github.com/fairlearn/fairlearn/pull/1451

MNT Fix CorrelationRemover failing estimator checks

---

fairlearn/metrics/_bootstrap.py
fairlearn/metrics/_disaggregated_result.py
test/unit/metrics/test_bootstrap.py
test/unit/metrics/test_metricframe_bootstrap.py

Fixes #1441 (Notice, that I do not implement the stratified sampling here, as it would be a new feature that could go intro a dedicated PR)
Hello this my attempt to implement the [suggested](https://github.com/fairlearn/fairlearn/issues/1441#issuecomment-2504665116) solution to fix bootstrapping:
> When the bootstrap replicate does not contain any elements from a given group, it should return np.nan, and we should use np.nanquantile to get the values of various *_ci quantities. This will yield valid quantiles (under the same assumptions as the standard bootstrap). I don't think that we should allow substituting some other default value (like 0 or 1) in this case, because that is likely to lead to wrong quantiles. This approach would be also backward compatible re. random seeds. One …

fix: bootstrapping with missing sampled value

---

examples/plot_grid_search_census.py

- related to #1069
- created during the sprint at PyLadiesCon

DOC Add a BibTeX reference to `plot_grid_search_census.py`; fix markdown

---

fairlearn/reductions/_exponentiated_gradient/exponentiated_gradient.py

During the PyLadiesCon fastlearn sprint, @TamaraAtanasoska and I paired on fixing the broken citation on the [fairlearn.reductions.ExponentiatedGradient](https://fairlearn.org/v0.11/api_reference/generated/fairlearn.reductions.ExponentiatedGradient.html#fairlearn.reductions.ExponentiatedGradient) page.

Fix exponentiated gradient citation

---

docs/conf.py
docs/contributor_guide/contributing_documentation.rst
docs/contributor_guide/development_process.rst
docs/contributor_guide/release.rst
docs/quickstart.rst
docs/user_guide/installation_and_version_guide/installation_guide.rst

Closes #731 
If this is merged, copying the python code blocks (>>>) or bash($) will leave the prompt and outputs out of the clipboard.
I inspired myself from the way `sklearn` does it.
I'm aware I'm reverting some recent changes concerning `.. prompt:: bash`, but it makes more sense in my opinion, since sphinx adds the prompt for us (we do not to add the $ in the `.rst`), and leaves it out of the copy.

doc: remove outputs and python and bash prompts

---

examples/plot_credit_loan_decisions.py

Fixes #1506
As pointed out by @sylvaincom in #1506, there's a missing backtick to render text in italics, which prevents a citation from displaying correctly in `examples/plot_credit_loan_decisions.html`. This PR adds the backtick.
I've rebuilt the html documentation to check that it now displays correctly.

DOC Fixes backtick typo for footnote display

---

docs/user_guide/installation_and_version_guide/v0.13.0.rst
test_othermlpackages/test_pytorch.py
test_othermlpackages/test_xgboost.py

As #1459 outlines, we had issues with some packages not being compatible with the newest scikit-learn version. `Xgboost` has issued a release that covers these updates so we can remove skipping the tests.
Unfortunately no changes for `pytorch` or `tensorflow` yet.

MNT Enable xboost testing with sklearn 1.6 again

---

fairlearn/utils/_input_validation.py
test/unit/utils/test_utils.py

Towards #1522 . Discovered while working on narwhalifying `utils/_input_validation`, I think this can safely go to `main`
Given that the input and output  are `np.ndarray`s we can skip going via pandas.

MNT remove `pandas` from `_merge_columns`

---

fairlearn/metrics/__init__.py

I saw that some linting pipelines are failing the linting-ruff job (eg, https://github.com/fairlearn/fairlearn/actions/runs/13834889623/job/38732324210?pr=1478 and https://github.com/fairlearn/fairlearn/actions/runs/13852686923/job/38821917874?pr=1527). This is an attempt to fix it.

MNT remove extra noqa

---

scripts/install_requirements.py

I am not sure how the newline was deleted, but it is necessary, somehow got lots between the commits. Otherwise the `requirements.txt` cannot be written properly. I am so sorry for the inconvenience. 
ping @riedgar-ms and @adrinjalali with regards to #1491

FIX Add newline to the pinned numpy req in install_requirements

---

docs/contributor_guide/code_style.rst
docs/contributor_guide/contributing_code.rst
docs/contributor_guide/contributing_documentation.rst
docs/contributor_guide/index.rst

Addresses #952 to improve the code style guide within the contributor guide. Adds a new page named "code style" with the guidance mentioned in the issue, and adds references to this page throughout the contributor guide.
Requesting inputs from @taharallouche, @hildeweerts, and @TamaraAtanasoska on whether I left any important information out!

DOC Improving code style guide

---

requirements.txt

To make `fairlearn` fully `scipy` 1.16.0 compatible, we would need to add some changes to the codebase. 
In order to not stall the merging of some other outstanding PRs, I propose to temporarily limit the version until someone can pick it up to update some of the issues that arise. 
Here is a relevant issue #1562.
I would love to move a few things forward(including merging solutions for bugs etc.) and have a green `CI` for next week at EuroPython where I hope to meet and talk with folks about the library after the presentation. If someone has the time to fix the `scipy` issues this week, that would be amazing, but it can also wait for a few weeks. I can take a look after I am back from EuroPython.

MNT Temporarily limit scipy version to less than 1.16.0
