- .gitignore
- test_fairlearn_smoke.py
Convert the existing set of tests to PyTest
Also add a .gitignore file
> Convert tests to PyTest

- azure-pipelines.yml
- fairlearn/classred.py
- fairlearn/moments.py
- requirements.txt
- test_fairlearn.py
- test_fairlearn_smoke.py
Enable flake8 as a build task in the repo
Apply required fixes to existing files
- Run VS Code autoformat
- Fix overly long lines
> Enable flake8

- test/simple_learners.py
- test/test_fairlearn_smoke.py
Move the toy learner into its own file
> Refactor test learner into separate file

- azure-pipelines.yml
Experiment with adding a nightly build of our two main branches
> Add nightly build

- README.md
apparently github requires empty lines before tables
> fix broken README.md

- requirements.txt
Split requirements.txt into sections
Add missing dependencies
> Update and refactor requirements.txt

- azuredevops/code-coverage.yml
- requirements.txt
Adding a basic code coverage build
> Add Code Coverage build

- azuredevops/code-coverage.yml
Try to stop code coverage triggering on pushes to all branches
> Code Coverage Triggers

- fairlearn/reductions/grid_search/grid_search.py
- test/reductions/grid_search/test_grid_search_arguments.py
Ensure that Grid Search allows Python lists for the y and aux_data arguments
> Support for Python lists in Grid Search

- notebooks/Grid Search for Binary Classification.ipynb
- notebooks/Grid Search with Census Data.ipynb
- test/reductions/grid_search/test_grid_search_arguments.py
- test/reductions/grid_search/test_grid_search_classification.py
- test/reductions/grid_search/test_grid_search_regression.py
Add some extra GridSearch tests which target the Lagrange multipliers
> Testing Lagrange multipliers for GridSearch

- fairlearn/reductions/__init__.py
- fairlearn/reductions/grid_search/grid_search.py
- fairlearn/reductions/reductions_estimator.py
Keeping up with general change of 'learner' to 'estimator' to conform to common usage
> Rename ReductionsLearner to ReductionsEstimator

- README.md
Added typical badges.
Opened this against Roman's PR branch so the readme.md should be the latest.
Looks like this:
Issue: #38
> added badges at top of readme for build stats, mit license and pypi

- azuredevops/notebooks.yml
- requirements.txt
Build which runs all notebooks through pytest
> Build Definition for Notebooks

- azuredevops/notebooks.yml
- notebooks/Grid Search for Binary Classification.ipynb
- notebooks/Grid Search with Census Data.ipynb
- notebooks/ROC Curve based Post-Processing for Binary Classification.ipynb
Fixes to get the Notebook build working
> Notebook Build Fixes

- fairlearn/reductions/moments/bounded_group_loss.py
- fairlearn/reductions/moments/conditional_opportunity.py
- fairlearn/reductions/moments/moment.py
This PR contains an initial implementation of BGL and also introduces the basis generation support within moments.
Basis generation is required to integrate moments and GridSearch. The current implementation should be enough to get started.
> add BGL and basis handling in moments

- README.md
add ref to pypi 0.2.0 for current release, mention current work, at top:point to info for current users and add bz as maintainer
> Updates to readme, incl Miro items

- README.md
Remove badge with "dev" and change to nightly build
> Chg test badge to Azure Pipelines badge

- README.md
> add pypi badge that automatically sets the version number

- notebooks/Grid Search with Census Data.ipynb
Get "male" and "female" labelled properly in the dashboard for the census notebook
> Proper Labels in Dashboard for Census

- README.md
- setup.py
> Repo move updates

- devops/schedule-test.yml
Having trouble with Azure Pipelines; this is a test for a workaround
> Schedule Testing

- devops/code-coverage.yml
- devops/nightly.yml
This is an attempt to get the schedule triggers to work following the org move
> Add a comment to pipeline YAMLs

- fairlearn/reductions/exponentiated_gradient/exponentiated_gradient.py
- fairlearn/reductions/moments/__init__.py
- fairlearn/reductions/moments/conditional_selection_rate.py
- fairlearn/reductions/moments/error_rate.py
- notebooks/Grid Search with Census Data.ipynb
- test/unit/reductions/exponentiated_gradient/test_expgrad_smoke.py
Further tidying in Reductions
- Rename the moment `MisclassificationError` to `ErrorRate`
- Remove unimplemented methods from `ExponentiatedGradient`
- Make `predict_proba` private (and rename)
> Tidy up reductions

- fairlearn/metrics/group_metric_result.py
- fairlearn/metrics/mean_predictions.py
- fairlearn/metrics/metrics_engine.py
- fairlearn/post_processing/post_processing.py
- fairlearn/post_processing/threshold_optimizer.py
- fairlearn/reductions/exponentiated_gradient/exponentiated_gradient.py
- fairlearn/reductions/grid_search/grid_search.py
Experimenting with available documentation markup
> Documentation tweaks

- .gitignore
- docs/conf.py
- requirements.txt
- scripts/build-docs.ps1
Add a Powershell script which can build the documentation
Follows the pattern from AzureMLCli
> Script for building the docs

- devops/PR-Gate.yml
- devops/nightly-requirements-fixed.yml
- devops/nightly.yml
- devops/notebook-job-template.yml
Expand the notebooks build definitions to cover multiple versions of Python
> Python Versions for Notebooks

- fairlearn/widget/fairlearnDashboard.py
Support sensitive_features as 1d, and predicted_ys as 1d. Convert pd.Series to python list. warn if mismatch in size with non-needed parameter, and throw for needed parameter.
> Handle more input cases

- fairlearn/metrics/_mean_predictions.py
- test/unit/metrics/test_mean_predictions.py
Had a fix for `mean_underpredict` in master to flip sign to match expectations
> Cherry pick of mean_underpredict fix

- CONTRIBUTING.md
Update to use GitHub Community guidelines as Code of Conduct, and DCO validation
> Developer Certificate of Origin and Code of Conduct updates

- setup.py
The `setup.py` script was still pointing just at Miro.
> Update contact details

- CONTRIBUTING.md
Cherry pick into release branch
> Developer Certificate of Origin and Code of Conduct updates (#130)

- docs/conf.py
- fairlearn/__init__.py
> Update to 'full' version 0.3.0

- CHANGES.md
Add information about 0.3.0
Reformat dates
> Update Changes document

- CHANGES.md
Add information about 0.3.0
Reformat dates
> Cherry Pick update to Changes.md

- setup.py
Update the short description as agreed in meeting
> Update short description

- setup.py
> Update email address

- CONTRIBUTING.md
- README.md
Based on https://github.com/fairlearn/fairlearn/pull/116 which was too complicated to rebase for DCO, so resubmitting this.
> README update for v0.3.0 release

- CONTRIBUTING.md
- README.md
- setup.py
Cherry picks from master:
- `setup.py` contacts
- README and CONTRIBUTING revisions
> Cherry pick to Release

- CONTRIBUTING.md
Signed-off-by: Miro Dudik <mdudik@gmail.com>
> polish and fix contributing.md

- fairlearn/reductions/_grid_search/grid_search.py
- test/unit/reductions/exponentiated_gradient/test_expgrad_smoke.py
Put in some basic logging for GridSearch
Remove annoying console output from `ExponentiatedGradient` smoke tests
> Add logging for GridSearch

- fairlearn/__init__.py
> Add logging infrastructure

- fairlearn/reductions/_exponentiated_gradient/_lagrangian.py
- fairlearn/reductions/_exponentiated_gradient/exponentiated_gradient.py
- fairlearn/reductions/_grid_search/grid_search.py
Just some improvements in terms of documentation, and a few methods are prefixed with underscore if they're just helpers within a class.
> Exponentiated Gradient documentation updates

- fairlearn/__init__.py
> Increase version to 0.4.0

- fairlearn/__init__.py
> Change to an alpha release

- notebooks/Grid Search with Census Data.ipynb
Update the existing Census notebook for grid search to use the new dashboard. The bulk of the notebook is unchanged (including the fictional motivating scenario).
> Dashboard for Census Notebook

- devops/notebook-job-template.yml
- devops/notebook-pypi-job-template.yml
Have moved notebooks off the old dashboard. Remove dependency from pipelines
> Stop installing old dashboard

- README.md
Now that the dashboard tarball is no longer checked in, provide instructions on creating it in a cloned repo
> Update ReadMe with Yarn instructions

- fairlearn/widget/fairlearnDashboard.py
- fairlearn/widget/fairlearnWidget.py
Fix issues in getting documentation to appear in Sphinx
> Documentation fixes for Widget

- devops/PR-Gate.yml
- devops/build-widget-job-template.yml
- devops/nightly-requirements-fixed.yml
- devops/nightly.yml
Add a job template which builds the widget to the PR-Gate, Nightly and Nightly-Fixed builds. Note that this does not run any tests, but just ensures that the widget builds successfully
> Build the widget

- docs/conf.py
- docs/fairlearn.metrics.rst
- docs/fairlearn.postprocessing.rst
- docs/fairlearn.reductions.rst
- docs/fairlearn.rst
- docs/fairlearn.widget.rst
- docs/index.rst
- docs/modules.rst
- fairlearn/reductions/_exponentiated_gradient/exponentiated_gradient.py
- fairlearn/reductions/_grid_search/grid_search.py
- fairlearn/reductions/_moments/conditional_selection_rate.py
- fairlearn/reductions/_moments/moment.py
Change how the documentation is done slightly, so that our documentation can show up on ReadTheDocs. Some additional copy-editing of the in-code documentation has been done as a result of this.
The branch for this pull-request can be seen at:
https://fairlearn.readthedocs.io/en/riedgar-ms-readthedocs/
> Enable ReadTheDocs

- README.md
> Update readme for v0.4.0

- test/perf/metric_logging_script_expgrad_gridsearch.txt
- test/perf/metric_logging_script_postprocessing.txt
- test/perf/script_generation.py
The new metrics will show the overhead added by fairlearn. #225 
> Perf tests: readability improvements & more metrics

- docs/conf.py
- fairlearn/reductions/_moments/bounded_group_loss.py
- fairlearn/reductions/_moments/conditional_selection_rate.py
- fairlearn/reductions/_moments/moment.py
- test/unit/reductions/moments/test_moments_demographic_parity.py
- test/unit/reductions/moments/test_moments_equalized_odds.py
Add some basic documentation of the `Moment` class and its subclasses.
Also:
- Turn the `n` field of the `Moment` object into an `total_samples` property
- Add `intersphinx` hook for `pandas` documentation
> Basic Moments documentation

- CONTRIBUTING.md
- devops/templates/build-widget-job-template.yml
- devops/templates/code-coverage-job-template.yml
- devops/templates/create-wheel-step-template.yml
- devops/templates/pypi-deployment-stages-template.yml
Broken from recent restructuring, fixing now for v0.4.2 release.
> Fix pypi release yaml

- CHANGES.md
- CONTRIBUTING.md
- fairlearn/__init__.py
- scripts/process_readme.py
- test/unit/reductions/grid_search/test_grid_search_regression.py
> add CHANGES.md for v0.4.2

- devops/templates/build-widget-job-template.yml
- devops/templates/create-wheel-step-template.yml
- scripts/build_widget.py
- fixed widget build validation
> Fix release blockers - widget generated files, widget validation

- devops/templates/create-wheel-step-template.yml
> remove --assert-no-changes flag in release as well

- CHANGES.md
- README.md
- fairlearn/__init__.py
Bump version and update Markdown files
> Preparations for v0.4.3 Release

- Makefile
Decoupling a few changes I made in #282, to make it easier to merge and progress.
This makes a few improvements to the makefile, and adds some commands.
> MNT makefile improvements

- CHANGES.md
- README.md
- fairlearn/__init__.py
- fairlearn/metrics/_group_metric_set.py
- test/unit/metrics/test_create_group_metric_set.py
Update `create_group_metric_set` so that it embeds a schema type and version
Update the package version in preparation for release
> Update for create_group_metric_set and version update

- test/unit/postprocessing/test_plots.py
> use TKAgg only on MacOS

- AUTHORS.md
I noticed the doc says when people get a patch in, they should add themselves here. So I did, is this the right thing to do?
ping @romanlutz
> DOC add Adrin to authors.md

- README.md
- fairlearn/__init__.py
This is in preparation for the next release. Update the `__init__.py` and the `README.md` for this.
> Bump version to 0.4.5

- README.md
- fairlearn/__init__.py
This reverts commit bc8dd7aa7a6e6afb05edd45220ed5d64f44b2198.
> Revert "Bump version to 0.4.5 (#360)"

- CHANGES.md
> Add changelog for metrics at v0.4.6

- AUTHORS.md
> update author link

- fairlearn/reductions/_exponentiated_gradient/exponentiated_gradient.py
Addition of Lagrangian lambda in exponentiated gradient object. This helps us access the values of Lagragian lambdas from exponentiated gradient object directly.
> Add Lagrangian lambdas to exponentiated gradient object

- .github/workflows/run-notebook-tests-on-last-released-version.yml
This was a remnant from copy-pasting before.
> Fix naming in GitHub Action

- .circleci/config.yml
Remnant from switching over to fairlearn from forks
> Point to the fairlearn repos in CircleCI as opposed to forks

- devops/README.md
Add a short ReadMe file to the `devops` directory.
Closes #313 .
> ReadMe for Pipelines

- CHANGES.md
Missed this in the PRs by @hannanabdul55 and @parul100495 
> update CHANGES.md with updates on moments

- README.md
- fairlearn/__init__.py
Moving up to the next version in preparation for release.
> Bump version to v0.4.6

- notebooks/Binary Classification with the UCI Credit-card Default Dataset.ipynb
- scripts/requirements_pin.py
- test/notebooks/test_notebooks.py
- test/unit/fixes.py
- test/unit/reductions/grid_search/test_grid_search_arguments.py
Addressing broken builds
- Fix new `flake8` issue
- Add checks for the UCI Credit Card notebook
- Workaround `sklearn` and `LightGBM` issue in the UCI Credit Card notebook
- Support changing exception message for bad array shapes in `sklearn`
The fix for the changed exception message is ugly. We will need a better solution if this keeps happening.
> Build fixes

- docs/community/developer_call_notes/2020_05_07.rst
Adding the writeup - please comment if you want anything to be added/changed!
If there are no comments I'll complete the PR by Friday 5/22
> notes from first developer call

- visualization/FairnessDashboard/src/ChartColors.ts
- visualization/FairnessDashboard/src/Controls/AccuracyTab.styles.ts
- visualization/FairnessDashboard/src/Controls/AccuracyTab.tsx
- visualization/FairnessDashboard/src/Controls/BinDialog.styles.ts
- visualization/FairnessDashboard/src/Controls/BinDialog.tsx
- visualization/FairnessDashboard/src/Controls/DataSpecificationBlade.styles.ts
- visualization/FairnessDashboard/src/Controls/DataSpecificationBlade.tsx
- visualization/FairnessDashboard/src/Controls/FeatureTab.styles.ts
- visualization/FairnessDashboard/src/Controls/FeatureTab.tsx
- visualization/FairnessDashboard/src/Controls/IntroTab.styles.ts
- visualization/FairnessDashboard/src/Controls/IntroTab.tsx
- visualization/FairnessDashboard/src/Controls/ModelComparisionChart.styles.ts
- visualization/FairnessDashboard/src/Controls/ModelComparisonChart.tsx
- visualization/FairnessDashboard/src/Controls/SummaryTable.styles.ts
- visualization/FairnessDashboard/src/Controls/SummaryTable.tsx
- visualization/FairnessDashboard/src/Controls/TileList.styles.ts
- visualization/FairnessDashboard/src/Controls/TileList.tsx
- visualization/FairnessDashboard/src/Controls/WizardFooter.styles.ts
- visualization/FairnessDashboard/src/Controls/WizardFooter.tsx
- visualization/FairnessDashboard/src/FairnessWizard.styles.ts
- visualization/FairnessDashboard/src/FairnessWizard.tsx
- visualization/FairnessDashboard/src/Themes.ts
- visualization/FairnessDashboard/src/WizardReport.styles.ts
- visualization/FairnessDashboard/src/WizardReport.tsx
- visualization/test/test-page/App.jsx
This PR replaces hardcoded color and background with getTheme() from fluentUI
- this will support dark theme and dark theme contrast. 
- font size and weight has been replaced with FontSize and FontWeights from fluentUI.
> [fairlearn dashboard] Support fluentUI theme  

- visualization/FairnessDashboard/src/Controls/AccuracyTab.styles.ts
- visualization/FairnessDashboard/src/Controls/AccuracyTab.tsx
- visualization/FairnessDashboard/src/Controls/FeatureTab.styles.ts
- visualization/FairnessDashboard/src/Controls/FeatureTab.tsx
- visualization/FairnessDashboard/src/Controls/IntroTab.styles.ts
- visualization/FairnessDashboard/src/Controls/IntroTab.tsx
- visualization/FairnessDashboard/src/Controls/ModelComparisionChart.styles.ts
- visualization/FairnessDashboard/src/Controls/ModelComparisonChart.tsx
- visualization/FairnessDashboard/src/Controls/SummaryTable.tsx
- visualization/FairnessDashboard/src/Controls/TileList.styles.ts
- visualization/FairnessDashboard/src/Controls/TileList.tsx
- visualization/FairnessDashboard/src/FairnessWizard.styles.ts
- visualization/FairnessDashboard/src/WizardReport.styles.ts
- visualization/FairnessDashboard/src/WizardReport.tsx
The PR has minor styling changes related to color and font. Some screenshots to make it easy to review the pr.
**updated banner**
dark mode:
> Dark theme updates

- docs/contributor_guide/development_process.rst
Closes #314 raised by @adrinjalali 
> Document PR documentation requirements & numpydoc format switch

- scripts/build_widget.py
This currently involves all these steps to be run manually, so this script should make things easier.
> add build_widget.py extension to build local changes

- docs/contributor_guide/how_to_talk_about_fairness.rst
- docs/contributor_guide/index.rst
- docs/contributor_guide/ways_to_contribute.rst
- docs/user_guide/fairness_in_machine_learning.rst
Also contains a minor update to the first paragraph in the "fairness of AI systems" section.
> Add fairness styleguide

- docs/contributor_guide/developer_call_notes/2020_06_11.rst
- docs/contributor_guide/developer_call_notes/index.rst
I copied the notes from hackmd and added a little bit of context where needed (especially for folks who couldn't make it). If there's anything you'd like changed please point it out. I'm planning to leave this open until Thursday 6/18 EOD unless there are issues with it.
> Add developer call notes 06/11/2020

- docs/api_reference/fairlearn.datasets.rst
- docs/api_reference/index.rst
- fairlearn/datasets/__init__.py
- fairlearn/datasets/_fetch_boston.py
- fairlearn/exceptions.py
The previous PR https://github.com/fairlearn/fairlearn/pull/434 did not work for me. Something went wrong in git and I kept hitting merge conflicts when pulling from master. I do not know what exactly went wrong in that PR but I figured a hard reset was easier.
> The Boston Dataset - Clean

- AUTHORS.md
Signed-off-by: Janhavi Mahajan <jamahaja@microsoft.com>
> Adding name to author.md

- devops/pypi-release-new.yml
- fairlearn/__init__.py
Updating the PyPI release pipeline to use the `TwineAuthenticate` task, rather than fetching things from Azure KeyVault.
> Connection update for PyPI Release Pipeline

- docs/contributor_guide/developer_call_notes/2020_07_09.rst
- docs/contributor_guide/developer_call_notes/index.rst
Will complete this by Thursday 7/16 towards the end of the day unless there are comments. Thanks!
@adrinjalali @marksoper @hannawallach @MiroDudik @hildeweerts @riedgar-ms
> add developer call notes from 2020-07-09

- docs/contributor_guide/development_process.rst
Instructions for DCO that are less fancy than the one quoted in the current version, but easier to follow for novices (myself included).
> Expand DCO documentation

- AUTHORS.md
- docs/user_guide/mitigation.rst
> Fix typo in mitigation docs

- fairlearn/datasets/__init__.py
- fairlearn/datasets/_fetch_bank_marketing.py
- test/unit/datasets/test_datasets.py
Signed-off-by: Gaurav Gupta <gaugup@microsoft.com>
> Add bank marketing dataset to fairlearn

- fairlearn/datasets/_fetch_bank_marketing.py
Signed-off-by: Gaurav Gupta <gaugup@microsoft.com>
> Correct description for bank marketing dataset

- docs/contributor_guide/developer_call_notes/2020_07_09.rst
- docs/contributor_guide/developer_call_notes/2020_08_13.rst
- docs/contributor_guide/developer_call_notes/index.rst
I'm planning to merge this by Friday 8/28 EOD. Comments regarding the UI changes proposal should go to the proposal PR itself.
> Developer call notes 2020-08-13

- devops/other-ml-packages.yml
- devops/templates/other-ml-job-template.yml
- test_othermlpackages/ReadMe.md
Add a pipeline for running the new `test_othermlpackages/` directory. This is separate from the main test suite, since each package has its own conda environment file, and hence each has its own separate job.
> Pipeline for testing other ML packages

- fairlearn/reductions/_exponentiated_gradient/exponentiated_gradient.py
- fairlearn/reductions/_grid_search/grid_search.py
Also moving this to numpydoc where needed.
> DOC: fix reductions documentation to include regression

- docs/conf.py
Had somehow forgotten to add Numpy to the Intersphinx dictionary.
> Add numpy inventory to Sphinx

- docs/contributor_guide/developer_call_notes/2020_10_08.rst
Minutes from the meeting on the 8th of October.
> Developer Call Notes 2020-10-08

- fairlearn/__init__.py
Set `__init__.py` on the release branch to the correct version
> Set version in release branch

- docs/conf.py
- docs/static_landing_page/index.html
Update the documentation for the v0.5.0 release (and make sure that the docs for that version are actually built)
> Update docs for v0.5.0

- devops/templates/other-ml-job-template.yml
- test_othermlpackages/conda-pytorch.yaml
- test_othermlpackages/test_pytorch.py
I added an example on how to use pytorch with fairlearn.
As there is no official sklearn wrapper around pytorch, I used skorch.
Open to feedback.
> Pytorch example

- docs/about/index.rst
Provide a BibTeX entry for the whitepaper which describes the Fairlearn package. As we shift to a more open governance model, this should be updated with a more general publication.
Inspired by #641
> Add citation information

- AUTHORS.md
- fairlearn/metrics/_group_metric_set.py
- test/unit/metrics/test_create_group_metric_set.py
> Fix issue when creating group metric sets for regressions

- docs/faq.rst
Add some more questions to the FAQ, based on a training course run at Microsoft.
> FAQ Update

- README.md
Had overlooked when making bumping code version.
> Fix Readme version

- fairlearn/metrics/_disparities.py
- notebooks/ReadMe.md
This PR fixes a broken link in `notebooks/ReadMe.md` and corrects two docstrings to point to slightly more relevant information.
> Doc improvements

- docs/conf.py
- requirements-dev.txt
Closes #570 
WIP: Need to wait for `pydata-sphinx-theme` new release. Opening a PR now to keep me from forgetting.
> MAINT: Bump pydata-sphinx-theme; redirect logo link from ToC to landing page

- devops/templates/build-widget-job-template.yml
Having trouble with locating `yarn` on the build machines.
> CI Fix Build-Widget job

- docs/faq.rst
- docs/user_guide/assessment.rst
- docs/user_guide/mitigation.rst
While doing this update I also noticed that there was no entry for preprocessing in the corresponding table that I was linking to, so I quickly added that. Obviously, we'll need to add a user guide at some point.
@MiroDudik may want to take a look since he suggested that I create this PR in the first place :-)
> Add updates to FAQ for multi class classification and multiple/non-binary sensitive features

- README.md
- docs/static_landing_page/index.html
- fairlearn/__init__.py
This PR updates the versions for the release branch. There will be a separate PR for the `main` branch.
> Release adjustments for v0.6.2

- docs/quickstart.rst
- fairlearn/reductions/_exponentiated_gradient/exponentiated_gradient.py
The `.fit()` method currently doesn't return `self`. This PR changes that.
> Return self in .fit() in ExponentiatedGradient

- docs/contributor_guide/contributing_documentation.rst
Current guide is specific to Windows OS. 
Issue #805
> Improve contributing_documention guide

- setup.cfg
CI should be allowed to ignore certain directories.
Closes #751
> Allow flake8 to ignore certain directories

- CHANGES.md
Adding missing CHANGES.md entries for changes made by @romanlutz and @koaning.
Fixing the formatting of @adrinjalali's entry since the file is currently still markdown, so ReST directive don't work.
> MNT update CHANGES.md before the v0.7.0 release

- README.md
- fairlearn/__init__.py
Following release guidelines: https://fairlearn.org/main/contributor_guide/release.html
> MNT version updates for 0.7.0

- AUTHORS.md
- docs/conf.py
Issue context: https://github.com/fairlearn/fairlearn/issues/764#issuecomment-864426159
Signed-off-by: kurianbenoy-aot <kurian.benoy@aot-technologies.com>
> Change year dynamically in sphinx docs

- fairlearn/datasets/_fetch_boston.py
I noticed this issue on scikit-learn https://github.com/scikit-learn/scikit-learn/issues/19657 and figured it makes sense to apply it here too.
> FIX Update documentation in _fetch_boston.py

- fairlearn/postprocessing/_tradeoff_curve_utilities.py
The comments ascending/increasing should have been descending/decreasing.
Closes #831
> Fix comment in postprocessing API documentation #831

- docs/user_guide/installation_and_version_guide/v0.7.1.rst
- fairlearn/reductions/_grid_search/grid_search.py
- test/unit/reductions/grid_search/test_grid_search_arguments.py
Fixes issue #940 
Please see the issue for more details.
> Fixed bug when using custom Lagrange multipliers #940

- test/unit/preprocessing/linear_dep_remover/test_sklearn_compat.py
Signed-off-by: MiroDudik <mdudik@gmail.com>
> BUG remove unused import of pytest

- fairlearn/metrics/_metric_frame.py
Added an example for the MetricFrame class showcasing all methods.
related to #944
> DOC: example MetricFrame class #944

- fairlearn/metrics/_make_derived_metric.py
Fixes a small typo in the docstrings
> DOC fix typo in _make_derived_metric.py docstring

- fairlearn/metrics/_make_derived_metric.py
Added the list of possible options for the transformation parameter in make_derived_metric API ref.
> [DOC] List valid transforms for make_derived_metric

- fairlearn/metrics/_metric_frame.py
> Typo correction

- .circleci/config.yml
Make sure `apt` is up-to-date as well.
> Extra fix for doc build

- .github/PULL_REQUEST_TEMPLATE.md
Adding a PR template according to #1050. If you have feedback on the contents do let me know! @fairlearn/fairlearn-maintainers 
closes #1050
> Create a Pull Request Template

- .circleci/config.yml
Need to put the GitHub SSH keys into the right `known_hosts` file before we can push our docs.
> Update known_hosts for doc build

- .circleci/config.yml
Use the instructions for getting SSH access to a CircleCI job:
https://circleci.com/docs/2.0/ssh-access-jobs/
This suggests that the file creation is a multistep process
> Further SSH fiddling

- .circleci/config.yml
Try installing and running `gh-pages` as a regular user without sudo
> [Doc] Try running doc publish without sudo

- docs/user_guide/installation_and_version_guide/v0.8.0.rst
Had previously neglected to mention the `MetricFrame` performance improvements in the release notes.
> Update release notes for MetricFrame performance improvements.

- .circleci/config.yml
- devops/circle/push_doc.sh
closes #1071 
closes https://github.com/fairlearn/fairlearn/pull/1067
> CI fix doc deploy (from: #1071) 

- .circleci/config.yml
This got lost in the recent CI fix #1071 so I'm adding it back. I check and it does indeed fix the website so this is definitely needed and useful.
> CI fix website build by disabling jekyll build

- .circleci/config.yml
- devops/circle/push_doc.sh
This should fix the jekyll/css issues.
cc @romanlutz @riedgar-ms
> MNT move creating nojekyll to the push script

- docs/conf.py
- requirements-dev.txt
I suspect this should fix https://github.com/fairlearn/fairlearn/issues/1089
Let's see.
Closes https://github.com/fairlearn/fairlearn/issues/1089
> CI add numpydoc to doc build

- docs/_static/versions.json
Fixing more links for the docs.
> FIX fixing more links

- fairlearn/metrics/_group_metric_set.py
- fairlearn/metrics/_metric_frame.py
- test/unit/metrics/test_create_group_metric_set.py
- test/unit/metrics/test_metricframe_multiclass.py
- test/unit/metrics/test_metricframe_nonscalar.py
Refactoring `MetricFrame` slightly, taking some changes from #1038 . Also addresses a number of warnings emitted by the tests and removes unused constants.
> MetricFrame refactoring

- .github/workflows/build-test.yml
- fairlearn/metrics/_balanced_root_mean_squared_error.py
- fairlearn/metrics/_plotter.py
- fairlearn/reductions/_grid_search/grid_search.py
Add an extra job to the GitHub Action which forms our PR gate to also run flake8 on the codebase. This was done in the ADO pipelines, but is apparently not yet done in GitHub.
Fix some files which had line length violations.
> [Build] Add linting to gate

- docs/faq.rst
- docs/refs.bib
- docs/user_guide/assessment.rst
- fairlearn/metrics/_extra_metrics.py
- fairlearn/metrics/_make_derived_metric.py
- fairlearn/metrics/_metric_frame.py
- fairlearn/metrics/_selection_rate.py
Working on refactoring the Assesment docs, based on #1095 and #1114. This is the first stage in the process, redrafting and reorganising some sections. A few link targets have also changed, requiring small changes in some of the other files.
> Doc Refactor: Assessment Improvements

- fairlearn/reductions/_moments/utility_parity.py
- test_othermlpackages/conda-tensorflow.yaml
Discussed in the Community Call, related to issues with #1079 :
- Kills off a warning from `Moments`
- Changes how TensorFlow is installed, since the PyPI version was insisting on a GPU
> [Bug] Broken othermlpackages build

- docs/user_guide/assessment/common_fairness_metrics.rst
- docs/user_guide/fairness_in_machine_learning.rst
Reorganise the Common Fairness Metrics section, and move the discussion of the Four-Fifths rule here.
> [Doc] Reorganisation of Common Fairness Metrics

- .github/workflows/build-otherml-packages.yml
The `test_othermlpackages` directory has explicit conda environments for the different packages. This requires a custom workflow to run, which is ported from Azure Dev Ops.
> [BUILD] Port 'Other ML Packages' build

- .github/workflows/build-otherml-packages.yml
- codecov.yml
- test_othermlpackages/conda-lightgbm.yaml
- test_othermlpackages/conda-pytorch.yaml
- test_othermlpackages/conda-tensorflow.yaml
- test_othermlpackages/conda-xgboost.yaml
Some new PRs have code which targets packages such as PyTorch. To make our code coverage useful, we therefore need to have the `otherml_packages` build upload its coverage as well.
> [BUILD] Add code coverage to OtherML build

- docs/refs.bib
- docs/user_guide/assessment/perform_fairness_assessment.rst
- docs/user_guide/fairness_in_machine_learning.rst
More tweaking of the Assessment section. The biggest change is to re-list the definitions of allocation and quality of service harms, and then expand the 'Types of Harm' portion of 'Fairness in Machine Learning' (to avoid the former simply copying the latter. And to let me reference a very good book about stereotyping harms). This continues the work identified by #1114 .
> [DOC] Further Assessment Updates

- .github/workflows/release-wheel.yml
- docs/_static/versions.json
- docs/contributor_guide/release.rst
- docs/static_landing_page/js/landing_page.js
- docs/user_guide/installation_and_version_guide/v0.8.0.rst
- docs/user_guide/installation_and_version_guide/v0.9.0.rst
- fairlearn/__init__.py
Updating bits & pieces to reflect that `v0.8.0` is (about to be) released, and `v0.9.0` is the new development version.
There will be a follow up PR to get the docs straightened out (which will be cherry picked to the `release/v0.8.X` branch)
> [Release] Update main for v0.8.0

- .github/workflows/build-test.yml
Update the version of CodeCov Action used to the latest.
> Update CodeCov action

- .circleci/config.yml
Still trying to fix the landing page links. Need to persist the JS file to the workspace explicitly.
> FIX Further attempt to fix landing page links

- .circleci/push_doc.sh
The script was not pushing docs if there were no changes to the JS directory, since in those cases, the `git` commands on the directory were returning errors back to the shell.
> CI Try to improve handling of JS directory

- docs/_static/versions.json
- docs/conf.py
Attempt at cherry picking bad source links fix.
Resolve #1150 by adjusting how documentation links are generated
> [DOC] fix bad source links (#1151)

- docs/_static/css/custom.css
- docs/_static/versions.json
- docs/conf.py
- requirements-dev.txt
Upgrade sphinx theme in v0.8.x docs, from #1152
resolves #1134 resolves #1112
> DOC Upgrade pydata_sphinx_theme to v0.12.0 in Release/v0.8.x

- fairlearn/reductions/_exponentiated_gradient/_lagrangian.py
- test/unit/reductions/exponentiated_gradient/test_pickle.py
- test/unit/reductions/grid_search/test_pickle.py
This is just a helper PR to merge #662 (because the originating repository was deleted).
> Complete work on "Ensure Reductions can be pickled #662"

- docs/conf.py
- fairlearn/metrics/_disaggregated_result.py
- fairlearn/preprocessing/_correlation_remover.py
- pyproject.toml
- requirements-dev.txt
- test/install/test_no_matplotlib.py
- test/unit/metrics/test_metricframe_deprecate.py
- test/unit/reductions/grid_search/test_grid_search_regression.py
Signed-off-by: Miro Dudik <mdudik@gmail.com>
Fix warnings coming up in build tests.
> FIX test warnings

- pyproject.toml
- test/unit/reductions/moments/test_moments_control_features.py
- test_othermlpackages/package_test_common.py
- test_othermlpackages/test_pytorch.py
- test_othermlpackages/test_tensorflow.py
There are two UserWarnings left, but I'll leave fixing those for a future PR. One is related to handling of randomization inside AdversarialMitigator and requires a bit more work to fix. The other one is related to distutils and I'm not quite sure which of our dependencies is causing it.
> FIX UserWarnings in tests

- setup.py
These haven't been updated since the project started so it's about time.
@fairlearn/fairlearn-maintainers
> MNT Update setup.py with latest maintainers, email address and description

- docs/about/index.rst
- docs/faq.rst
- docs/refs.bib
- docs/user_guide/assessment/index.rst
- docs/user_guide/datasets/boston_housing_data.rst
- docs/user_guide/datasets/diabetes_hospital_data.rst
- examples/plot_credit_loan_decisions.py
Continuing with #1069. I didn't quite know whether the remaining ones at the bottom of the page should stay as is or also get converted to bibtex. I can't find existing bibtex entries for them since they're just blog posts etc.
I also just realized we don't always use `:footcite:` but sometimes additional specifications like `:footcite:p:`. If you have suggestions/thoughts please submit comments or directly commit them. @MiroDudik 
I would also love to order the bibtex file by alias, but that will have to happen in a separate PR for readability reasons.
> DOC convert a few more references to bibtex

- requirements-dev.txt
closes #1160 
flake8-copyright released a fix recently that unblocks this change.
> MNT remove pins on flake8 and autopep8

- fairlearn/datasets/_fetch_acs_income.py
- fairlearn/datasets/_fetch_adult.py
- fairlearn/datasets/_fetch_bank_marketing.py
- fairlearn/datasets/_fetch_boston.py
- fairlearn/datasets/_fetch_credit_card.py
- fairlearn/datasets/_fetch_diabetes_hospital.py
This is my good first issue:) The goal is to address Issue #1205 created by @romanlutz. This is just example for one dataset (ACS Income dataset). Once confirmed, will do for the other datasets.
- [] user guide added or updated
- [X ] API docs added or updated
> DOC Fixing the issue with return_X_y in documentation for fetch datasets (ACS Income dataset)

- .github/workflows/linting.yml
- .pre-commit-config.yaml
- fairlearn/adversarial/_adversarial_mitigation.py
- fairlearn/metrics/__init__.py
- fairlearn/metrics/_make_derived_metric.py
- fairlearn/metrics/_metric_frame.py
- fairlearn/metrics/_plot_model_comparison.py
- fairlearn/postprocessing/_interpolated_thresholder.py
- fairlearn/postprocessing/_threshold_optimizer.py
- fairlearn/postprocessing/_tradeoff_curve_utilities.py
- fairlearn/reductions/_exponentiated_gradient/exponentiated_gradient.py
- fairlearn/reductions/_moments/utility_parity.py
- fairlearn/utils/_compatibility.py
- pyproject.toml
- requirements-dev.txt
- scripts/install_requirements.py
- scripts/process_readme.py
- setup.py
- test/unit/adversarial/helper.py
- test/unit/adversarial/test_adversarial_mitigation.py
- test/unit/metrics/test_plot_model_comparison.py
- test/unit/metrics/test_selection_rate.py
- test/unit/reductions/exponentiated_gradient/test_pickle.py
- test/unit/reductions/grid_search/test_grid_search_arguments.py
- test/unit/reductions/grid_search/test_grid_search_demographicparity.py
- test/unit/reductions/grid_search/test_grid_search_regression.py
- test/unit/reductions/grid_search/test_pickle.py
- test/unit/reductions/moments/test_moments_bounded_group_loss.py
- test_othermlpackages/test_pytorch.py
Run `black` on the repository, and add the requiste GitHub Action to keep this enforced.
> MNT Repository blackening and upgrade black version to 23.3.0

- docs/static_landing_page/index.html
> Changed the copyright year

- CITATION.cff
Add a citation file to the repository (see also #1252).
The .cff format is not super nice for arXiv papers as it does not include things such as `eprint` and `archivePrefix`, but it seems the most common way to deal with this is to add it as a journal article instead. Not perfect, but this citation is (hopefully) temporary until the paper gets accepted anyways.
APA
```
Weerts, H., Dudík, M., Edgar, R., Jalali, A., Lutz, R., & Madaio, M. (2023). Fairlearn: Assessing and Improving Fairness of AI Systems. arXiv preprint arXiv:2303.16626. https://arxiv.org/abs/2303.16626
```
BibTex
```
@article{Weerts_Fairlearn_Assessing_and_2023,
author = {Weerts, Hilde and Dudík, Miroslav and Edgar, Richard and Jalali, Adrin and Lutz, Roman and Madaio, Michael},
journal = {arXiv preprint arXiv:2303.16626}, …
```
> DOC add citation file

- fairlearn/show_versions.py
- test/unit/postprocessing/test_plots.py
I introduced flake8 failures in #1255 which this PR fixes.
> MNT fix flake8 issues

- .circleci/config.yml
- .github/workflows/release-wheel.yml
- .github/workflows/test-all-deps.yml
- docs/contributor_guide/contributing_documentation.rst
- docs/contributor_guide/development_process.rst
- requirements-customplots.txt
- scripts/build_wheels.py
- scripts/install_requirements.py
- setup.py
Taking a stab at #1186. It's likely that it needs more adjustments.
> MNT remove customplots extra

- docs/user_guide/installation_and_version_guide/v0.9.0.rst
Step 1 in the release of v0.9.0 :)
> DOC update version guide v0.9.0

- fairlearn/__init__.py
> Update version to 0.9.0

- .github/workflows/release-wheel.yml
- requirements-dev.txt
Copy #1256 to the release workflow, and leave a note about this in `requirements-dev.txt`
> MNT Lightgbm fix for release workflow

- .github/workflows/release-wheel.yml
- requirements-dev.txt
Cherry pick #1266 to release branch
> MNT Lightgbm fix for release workflow (#1266)

- .github/workflows/release-wheel.yml
Getting a strange error, which may be related to the comment. Mirroring the previous command more closely.
> MNT Further release workflow fixes

- .github/workflows/release-wheel.yml
> MNT Further release workflow fixes (#1268)

- .github/workflows/release-wheel.yml
Think about how shells do redirection
> Another fix for the release workflow

- .github/workflows/release-wheel.yml
> MNT Think about shell redirection (#1272)

- docs/_static/versions.json
- docs/static_landing_page/js/landing_page.js
- docs/user_guide/installation_and_version_guide/v0.10.0.rst
- fairlearn/__init__.py
Update main for release v0.9.0.
**Do not merge until the release is completed. Otherwise, a new website will be published that points to the new version which doesn’t exist yet.**
> MNT Update main for release v0.9.0

- docs/_static/versions.json
I forgot a slash, resulting in broken links for the docs for 0.9.0
> DOC forgot a slash

- docs/contributor_guide/release.rst
A few updates for the release guide based on my experiences.
> DOC Update release process contributor guide

- docs/about/maintainers.rst
Adding @alliesaizan to @fairlearn/fairlearn-maintainers ! 🙂
> DOC add Allie as maintainer!

- fairlearn/preprocessing/_correlation_remover.py
This addresses issue #949 , under the thread #855
> add: version added and version changed to fairlearn.preprocessing

- .circleci/config.yml
Python 3.8 is a little elderly for use in our documentation build. Update to the latest CircleCI offers
> Bump Python image in doc build

- test/unit/reductions/grid_search/test_grid_generator.py
Minor fix in a test to avoid a pandas warning, and have the code more efficient.
cc @riedgar-ms
> MNT fix pandas issue in test_grid_generator.py

- docs/contributor_guide/contributing_code.rst
This PR addresses issue #1236, and adds a paragraph to the beginning of the "Contributing Code" section of the documentation that describes what we look for in terms of adding new features. This is intended to be a starting point, and I anticipate reviewers will be able to add more context around the guidance we should give to contributors.
@hildeweerts @MiroDudik
> Adding guidance on contributing new methods

- fairlearn/reductions/_exponentiated_gradient/_lagrangian.py
- fairlearn/reductions/_grid_search/grid_search.py
- test/unit/reductions/exponentiated_gradient/test_exponentiatedgradient_arguments.py
- test/unit/reductions/exponentiated_gradient/test_exponentiatedgradient_smoke.py
- test/unit/reductions/exponentiated_gradient/test_lagrangian.py
Further small tweaks to address an onslaught of warnings from `pandas`. Fixes are in both the tests and in the product code.
> MNT Further pandas fixing

- setup.py
Adding @alliesaizan to the setup.py which we previously missed when she became a maintainer.
> DOC Update setup.py to reflect all maintainers

- .github/workflows/nightly.yml
Taking a swing at getting Nightly working again:
- Bring over the `codeCovPython` setting
- Make sure we also run with Python 3.11
> MNT Nightly Build Fixes

- requirements.txt
Taking another swing at the nightly build, bumping the lower requirement bounds to better reflect reality. It appears that these had been largely untouched since the dawn of Fairlearn.
> MNT Lower Bounds on requirements

- docs/user_guide/installation_and_version_guide/v0.10.0.rst
- docs/user_guide/installation_and_version_guide/v0.8.0.rst
- docs/user_guide/installation_and_version_guide/v0.9.0.rst
Updating the version log to reflect the current state in anticipation of our v0.10.0 release.
> DOC update version log to reflect recent changes

- docs/api_reference/index.rst
- docs/user_guide/installation_and_version_guide/v0.11.0.rst
- fairlearn/metrics/__init__.py
- fairlearn/metrics/_fairness_metrics.py
- test/unit/metrics/test_fairness_metrics.py
- test/unit/metrics/test_generated_metrics.py
Adding changes discussed in #1322
This is a basic proposal how Equal Opportunity metric could be added, following the same structure as Demographic Parity.
If this approach is accepted, I can add tests as well.
> ENH Adding Equal Opportunity to fairness metrics

- fairlearn/reductions/_moments/utility_parity.py
Trying to fix more issues, but there's an issue I can't figure out. Opened https://github.com/fairlearn/fairlearn/issues/1338 to discuss the issue.
> FIX more pandas issues

- .github/workflows/linting.yml
- .pre-commit-config.yaml
- fairlearn/metrics/_metric_frame.py
- requirements-dev.txt
This PR updates the version of the `black` linter to 24.4.2.
@adrinjalali
> MNT Update the version of black to 24.4.2

- .git-blame-ignore-revs
This PR updates the `.git-blame-ignore-revs` with the changes introduced in #1365.
@adrinjalali
> MNT Update .git-blame-ignore-revs with linting changes

- .github/workflows/release-wheel.yml
- requirements-dev.txt
The issue is fixed on the lightgbm side, so let's see if CI agrees.
> MNT remove lightgbm pin

- docs/conf.py
- docs/contributor_guide/development_process.rst
- docs/faq.rst
- docs/quickstart.rst
- docs/user_guide/datasets/boston_housing_data.rst
- docs/user_guide/installation_and_version_guide/v0.10.0.rst
- examples/plot_intersectional_bias.py
- examples/plot_plotting_metrics_with_error.py
- fairlearn/adversarial/_adversarial_mitigation.py
- fairlearn/datasets/_fetch_acs_income.py
- fairlearn/datasets/_fetch_adult.py
- fairlearn/datasets/_fetch_bank_marketing.py
- fairlearn/datasets/_fetch_credit_card.py
- fairlearn/postprocessing/_plotting.py
- fairlearn/postprocessing/_threshold_operation.py
- fairlearn/postprocessing/_tradeoff_curve_utilities.py
- fairlearn/reductions/_exponentiated_gradient/exponentiated_gradient.py
- fairlearn/reductions/_grid_search/grid_search.py
- test/unit/reductions/moments/data_generator.py
This PR clears the doc build from all warnings: 
Because of a conflict between the `napoleon` and `numpydoc` sphinx extensions which prompted the "`py:class reference target not found`"([more here](https://github.com/sphinx-doc/sphinx/issues/7391)), I removed the napoleon extension af9d1f968884732733874f10365368ff6993a230 and rewrote parts of the documentation in numpydoc style in f812ed4b75473b61ad1a2fe37c67c41ea232de6f.
This `numpydoc `class members suppression line in 275a70083b14938c025022f2aebd1ad58d5288c4 solves the `"autosummary: stub file not found"` warning, without changing the existing look of the documentation.
[Reference]( https://github.com/sphinx-gallery/sphinx-gallery/issues/120) for the solution for the`"image file not readable"` warning in …
> MNT DOC Clear docs build from all warnings

- .gitignore
- docs/api_reference/index.rst
- docs/conf.py
- docs/templates/function.rst
- fairlearn/experimental/__init__.py
- requirements.txt
This PR adds example gallery at the bottom of the API docs. First discussed in #1359.
Contains `numpy<2` limitation for CI to pass. 
@alliesaizan @adrinjalali
> MNT DOC Add example gallery to the API docs

- docs/user_guide/datasets/acs_income.rst
Updated the user-guide on acs-income to include usage information on the fetch_acs_income function.
Updated the user-guide on acs-income to include usage information on the fetch_acs_income function.
Fix mentioned in issue #1390.
@romanlutz @adrinjalali 
- [x ] no new tests required
> DOC Update acs_income.rst

- fairlearn/datasets/_fetch_acs_income.py
- test/unit/datasets/test_datasets.py
Hi all, I have noticed there was no test for `fetch_acs_income`. 
This PR adds some tests and also cleans up a bit the pandas code inside the function. 
Please let me know if there is something that I missed, thanks :)
> Add test for `fetch_acs_income`

- fairlearn/reductions/_moments/utility_parity.py
Hi all, this is a veeery small PR to remove some unused lines. `self.pos_basis` and `self.neg_basis` are also set in a couple of lines below :)
> Remove unused dataframe creation

- docs/contributor_guide/index.rst
Update the website to reflect new community call time
> [Doc] Tweak text about community calls

- fairlearn/adversarial/_adversarial_mitigation.py
- fairlearn/adversarial/_preprocessor.py
- test/install/test_no_ml.py
- test/unit/adversarial/helper.py
- test/unit/adversarial/test_adversarial_mitigation.py
This PR fixes all the remaining `scikit-learn` estimator checks, excluding the pickle errors that will come in a subsequent PR by itself. 
@adrinjalali check it out! I will add some comments where I have doubts.
> MNT Fix all remaining estimator checks (except pickle related errors)

- docs/about/maintainers.rst
Caution 🚨 : vain PR alert 
Adding myself to the "About us" maintainer section of the website :)
> DOC Add Tamara to the website

- docs/conf.py
- docs/jupyter-lite.json
- docs/jupyter_lite_config.json
- requirements-dev.txt
Closes https://github.com/fairlearn/fairlearn/issues/764 and https://github.com/fairlearn/fairlearn/pull/870, clarification for the reasoning here: https://github.com/fairlearn/fairlearn/pull/870#issuecomment-2441832544. 
@romanlutz please take a look if possible as the issue was yours.
> DOC Add jupyterlite button to the examples

- docs/user_guide/installation_and_version_guide/v0.11.0.rst
> Update changelog to prepare for v0.11.0

- docs/_static/versions.json
- docs/static_landing_page/js/landing_page.js
- fairlearn/__init__.py
Updates from the last section of the release guide.
**Do not merge until the release is completed. Otherwise a new website will be published that points to the new version which doesn’t exist yet.**
> Update required versioning changes (last release PR)

- docs/_static/versions.json
Fixing the folder <-> version issue.
@adrinjalali needs approval :)
> Fix website

- docs/static_landing_page/js/landing_page.js
@alliesaizan thanks for checking!
> Fix the link version (extra 0) attempt 2

- fairlearn/metrics/_disaggregated_result.py
- fairlearn/metrics/_metric_frame.py
This, imho, can be a small QoL improvement for the users whose IDEs might list the valid options when entering these arguments. It can also make the code more readable (no need to go through the doc string to figure out the valid options).
Please ignore if it doesn't match the repo's conventions (I don't want to be stepping over any toes here :sweat_smile:). More generally, if you prefer that I open issues to discuss the changes before opening PRs I'd be very happy to do it :pray:
> feat: add literals for compare method and error handling

- docs/user_guide/mitigation/preprocessing.rst
- fairlearn/preprocessing/_correlation_remover.py
Hi @TamaraAtanasoska @hildeweerts , I’ve updated the mathematical formulation in the doc to better match the optimization problem that the `CorrelationRemover` class is actually solving. WDYT ? :pray:
> fix: correlation remover docs

- docs/user_guide/installation_and_version_guide/v0.12.0.rst
- fairlearn/adversarial/_adversarial_mitigation.py
- fairlearn/preprocessing/_correlation_remover.py
- fairlearn/utils/_fixes.py
- fairlearn/utils/_input_validation.py
- pyproject.toml
- test/unit/adversarial/test_adversarial_mitigation.py
- test/unit/fixes.py
- test/unit/postprocessing/test_threshold_optimization.py
- test/unit/preprocessing/linear_dep_remover/test_sklearn_compat.py
This PR fixes https://github.com/fairlearn/fairlearn/issues/1446.
Pinging @adrinjalali for a review 🙏 .
@fairlearn/fairlearn-maintainers it would be great if we could soon make a release with these changes, as soon as `scikit-learn 1.6` is available.
Locally all tests for both versions pass, if CI comes up with anything else I will fix it asap.
> MNT scikit-learn 1.6 compatibility

- .github/workflows/check-changelog.yml
- .github/workflows/release-wheel.yml
- .github/workflows/test-all-deps.yml
- docs/conf.py
- docs/contributor_guide/development_process.rst
- docs/user_guide/installation_and_version_guide/v0.12.0.rst
- docs/user_guide/mitigation/postprocessing.rst
- fairlearn/postprocessing/_interpolated_thresholder.py
- fairlearn/postprocessing/_threshold_optimizer.py
- pyproject.toml
- requirements-dev.txt
- test/unit/adversarial/test_adversarial_mitigation.py
- test_othermlpackages/package_test_common.py
- test_othermlpackages/test_pytorch.py
- test_othermlpackages/test_tensorflow.py
- test_othermlpackages/test_xgboost.py
This PR adds a changelog entry check like `scikit-learn`'s, when a user affecting change is introduced. 
cc @adrinjalali, what do you think? I think this will make the release process a bit easier.
> MNT Prep fairlearn for release and add a changelog requirement to PRs

- docs/user_guide/installation_and_version_guide/v0.12.0.rst
Hello @TamaraAtanasoska here are the entries that I think are relevant. I didn't include the changes related to refactoring, type hints, and testing (namely the mitigation statistical testing PR) as they are not user-facing.
> add change log entries

- docs/about/maintainers.rst
This PR merges the output of `python scripts/generate_maintainers_table.py`, the first step of the release process.
ping @adrinjalali
> MNT Release step 1: Update maintainers file

- scripts/generate_maintainers_table.py
The script for generating the list of maintainers and the linting rules that we adopted since this script was created were in contradiction. Updated the script so they match and the linting is consistent.
@adrinjalali
> MNT Release step 1.2: Change script to be linting compliant

- fairlearn/__init__.py
This PR updates the `__init__.py` version in the release branch.
@adrinjalali
> MNT Release step 2: Update version as stated in the release guide

- docs/user_guide/installation_and_version_guide/v0.12.0.rst
This PR will remove the release notes "unreleased" from the release branch. In main it can be removed with the last PR of the release process when creating the next file.
> MNT Release: remove note from release notes

- docs/_static/versions.json
- docs/static_landing_page/js/landing_page.js
- docs/user_guide/installation_and_version_guide/v0.12.0.rst
- docs/user_guide/installation_and_version_guide/v0.13.0.rst
- fairlearn/__init__.py
This PR applies the following changes outlined in the guidelines:
```
- Update the version in __init__.py to x.y+1.z.dev0
- Update the version in docs/static_landing_page/js/landing_page.js so that all the links point to the new release
- Update the docs/_static/versions.json file
- Create a new file vx.y+1.z.rst in docs/user_guide/installation_and_version_guide
```
@adrinjalali
> MNT Release step 3: Apply versioning changes for the website to main

- docs/refs.bib
- docs/user_guide/assessment/perform_fairness_assessment.rst
- docs/user_guide/fairness_in_machine_learning.rst
- docs/user_guide/further_resources.rst
- examples/plot_new_metrics.py
- fairlearn/postprocessing/_tradeoff_curve_utilities.py
Addresses subtasks mentioned in #1069 :
> Adding references to ref.bib

- docs/refs.bib
- docs/user_guide/fairness_in_machine_learning.rst
Initial draft to start "Stakeholder identification" section of the user guide referenced in #1449 
@alliesaizan
> Re: DOC Start the "Stakeholder identification" section of the user guide

- docs/contributor_guide/development_process.rst
Drafted initial virtual env setup section for issue #1481 @TamaraAtanasoska please let me know if we need more troubleshooting instructions coverage/or show how to use miniconda to set up a virtual env also. Opening this as a draft PR to start. 
- [X ] no new tests required
- [ X] user guide added or updated
> Initial draft of virtualenv set up doc section for newcomers

- docs/contributor_guide/contributing_documentation.rst
- docs/contributor_guide/development_process.rst
This PR add some aesthetic dev process description changes, fixes naming inconsistencies and shortens the line for maintenance ease.
> DOC Update dev process instructions (fix naming inconsistencies and minor aesthetic changes)

- docs/contributor_guide/development_process.rst
fixes issue #1504.
Removed reference to AUTHORS.md by deleting the sentence which contains "AUTHORS.md" in the text.
> DOC Update development_process.rst

- docs/faq.rst
> DOC Update Python version to 3.9.

- examples/plot_adversarial_basics.py
…com/fairlearn/fairlearn/issues/1499
- Added cell block start to ensure correct rendering of explanatory text paragraph in notebook [plot_adversarial_basics.py](https://github.com/fairlearn/fairlearn/blob/main/examples/plot_adversarial_basics.py).
- This is to fix [issue 1499](https://github.com/fairlearn/fairlearn/issues/1499).
@TamaraAtanasoska fyi
- Rebuilt the changed page and it renders as desired:
> DOC Added cell block lines to fix formatting as per issue 

- docs/user_guide/assessment/common_fairness_metrics.rst
- docs/user_guide/datasets/acs_income.rst
- docs/user_guide/datasets/boston_housing_data.rst
- docs/user_guide/fairness_in_machine_learning.rst
- docs/user_guide/mitigation/adversarial.rst
- docs/user_guide/mitigation/postprocessing.rst
- docs/user_guide/mitigation/reductions.rst
Issue #1503
Changed reference block  from 
```
References
----------
.. footbibliography::
```
to 
```
.. topic:: References
.. footbibliography::
```
Edited files:
- docs/user_guide/assessment/common_fairness_metrics.rst
- docs/user_guide/datasets/acs_income.rst
- docs/user_guide/datasets/boston_housing_data.rst
- docs/user_guide/fairness_in_machine_learning.rst
- docs/user_guide/mitigation/adversarial.rst
- docs/user_guide/mitigation/postprocessing.rst
- docs/user_guide/mitigation/reductions.rst
@TamaraAtanasoska
> DOC fixed reference block of fairness_in_machine_learning

- examples/plot_intersectional_bias.py
> DOC fixed output and reference 

- test_othermlpackages/test_pytorch.py
`skorch` has fixed the issues that enable the testing again, comment https://github.com/fairlearn/fairlearn/pull/1517#issuecomment-2676335824. 
cc @adrinjalali 
updated the pinned issue https://github.com/fairlearn/fairlearn/issues/1459 to just point to `tensorflow` now
> MNT Enable testing for pytorch and sklearn 1.6 again

- README.rst
Part of #1481.
I restructured some of the information on the page.
cc @alliesaizan maybe you'd be up for a review?
@nnpereira let me know if you have any remarks!
> DOC Update the README to better serve different types of users and contributors

- docs/user_guide/mitigation/reductions.rst
> DOC replaced RandomForestClassifier with HistGradientBoostingCLassifier

- docs/contributor_guide/contributing_example_notebooks.rst
- docs/refs.bib
Fixes issue #1069 on aggregating references to the refs.bib file @TamaraAtanasoska
> DOC Added citations to contributing example notebooks and update refs.bib

- docs/conf.py
- docs/contributor_guide/contributing_documentation.rst
Addresses Improvements to Typographical Consistency and Grammar in Documentation #1367
> DOC Improvements to Typographical Consistency and Grammar in Documentation #1367

- docs/user_guide/mitigation/preprocessing.rst
- examples/plot_credit_loan_decisions.py
- fairlearn/adversarial/_adversarial_mitigation.py
- fairlearn/adversarial/_backend_engine.py
- fairlearn/datasets/_fetch_credit_card.py
- fairlearn/metrics/_metric_frame.py
- fairlearn/postprocessing/_threshold_optimizer.py
- fairlearn/reductions/_exponentiated_gradient/exponentiated_gradient.py
- fairlearn/utils/_common.py
- test/unit/preprocessing/linear_dep_remover/test_correlation_remover_efficiency.py
- test/unit/reductions/grid_search/test_grid_generator.py
Spotted a few and took it programmatically from there 🤗
> DOC: Various typos

- docs/conf.py
- docs/index.rst
- docs/static_landing_page/index.html
> DOC Add survey callout box to documentation index page (#1541)

- .circleci/config.yml
- docs/conf.py
- docs/contributor_guide/code_style.rst
- docs/contributor_guide/contributing_documentation.rst
- docs/user_guide/installation_and_version_guide/v0.13.0.rst
- docs/user_guide/mitigation/preprocessing.rst
- docs/user_guide/mitigation/reductions.rst
- fairlearn/metrics/_fairness_metrics.py
- requirements-dev.txt
- requirements-min.txt
The documentation build crashes because of memory exhaustion. 
The most effective solution is to increase the `resource_class` in CircleCI to `large`. Large is the default resource class for newer projects ([source](https://support.circleci.com/hc/en-us/articles/16463648743707-Why-do-some-projects-default-to-different-resource-classes?utm_source=chatgpt.com)) and with the amount of runs the project does we should be able to be ok with the free tier minutes. 
What will further reduce the minutes and demands:
- Merging https://github.com/fairlearn/fairlearn/pull/1539 would significantly reduce the memory usage and computation time of `plot_adversarial_fine_tuning ` up to several minutes less.
- `plot_adversarial_basics` can be optimised with general deep learning training resource saving …
> MNT Fix the doc build
